// bookLongQuestions.en.js
// HKDSE Biology — Book-level cross-topic long questions (English UK version)
// Loaded when the app language is English (UK). Structure matches bookLongQuestions.js (zh-HK).
// Each book has 5 cross-topic long questions (integrating knowledge from several chapters).

const LQ_BOOKS_EN = [
  {
    bookId: "1A",
    name: "Book 1A",
    range: "Chapters 01–05",
    questions: [
      { q: "A student observed different biomolecules and cells with a microscope.\n(a) Write down the positive results for testing starch, reducing sugar and protein with iodine solution, Benedict's solution and biuret reagent respectively.\n(b) Explain why enzymes are proteins, and why both high temperature and extreme pH make enzymes lose their activity.", marks: "6 marks", answer: "(a) Iodine with starch: brown → blue-black; Benedict's solution with reducing sugar after heating: brick-red precipitate; biuret reagent with protein: purple.\n(b) Enzymes are proteins; high temperature and extreme pH break down the spatial structure of the protein (hydrogen bonds), denaturing the enzyme, so the shape of the active site changes, it cannot bind to the substrate, and its catalytic activity is lost irreversibly." },
      { q: "An athlete felt muscle ache after vigorous exercise.\n(a) Explain the cause of the muscle ache.\n(b) State the relationship of this phenomenon with the transport of substances across cell membranes (Chapter 4) and enzymes (Chapter 5).", marks: "5 marks", answer: "(a) During vigorous exercise the oxygen supply is insufficient, so the muscles carry out anaerobic respiration and produce lactic acid; the accumulation of lactic acid causes the ache.\n(b) Without enough oxygen, aerobic respiration is blocked, and the carrier proteins on the cell membrane that transport substances consume less ATP; the respiratory enzymes cannot complete the aerobic breakdown of glucose, so only glycolysis occurs, producing lactic acid." },
      { q: "Compare the structures of plant cells and animal cells, and explain why the two react differently in a hypotonic solution.", marks: "6 marks", answer: "Plant cells have a cell wall (cellulose), a large central vacuole and chloroplasts; animal cells do not. Both have a cell membrane, cytoplasm, nucleus and mitochondria.\nIn a hypotonic solution water enters the cells: animal cells have no cell wall and swell and may even burst; plant cells have a rigid cell wall, so they become turgid (turgor pressure rises) without bursting, providing support for the plant." },
      { q: "Explain the joint importance of water and enzymes in organisms, giving one example of each.", marks: "5 marks", answer: "Water: a good solvent and transport medium; a reactant in metabolic reactions (e.g. photosynthesis, hydrolysis); acts as a coolant regulating body temperature; buffers temperature changes; provides support.\nEnzymes: biological catalysts that lower the activation energy and speed up metabolic reactions, so reactions proceed quickly at low temperature, e.g. salivary amylase breaks down starch.\nBoth are indispensable to life." },
      { q: "A student calculated the magnification under a microscope. The eyepiece magnification is 10X and the objective is 40X.\n(a) Calculate the total magnification.\n(b) What unit should be used to measure the actual size of a cell? Why?\n(c) Explain why the image is darker at high magnification.", marks: "4 marks", answer: "(a) Total magnification = 10X × 40X = 400X.\n(b) Micrometre (μm), because cells are very small and a smaller unit is more convenient and accurate.\n(c) At high magnification the field of view is smaller, so less light enters the eye and the image is darker." }
    ]
  },
  {
    bookId: "1B",
    name: "Book 1B",
    range: "Chapters 06–09",
    questions: [
      { q: "A student used the villi of the small intestine as an example to explain the absorption of food.\n(a) Write down how glucose, amino acids and the products of fat digestion are absorbed.\n(b) Explain how the structural features of the villi match the absorptive function.", marks: "6 marks", answer: "(a) Glucose and amino acids enter the villus epithelial cells by active transport (or facilitated diffusion) and then diffuse into the capillaries; the products of fat digestion (fatty acids and glycerol) enter the lacteals of the villi.\n(b) The villi provide a large surface area; the wall is thin (a single layer of cells), shortening the diffusion distance; the rich capillaries quickly carry away absorbed substances, maintaining a concentration gradient; the lacteals absorb the products of fat digestion." },
      { q: "A patient with tuberculosis was infected through droplets.\n(a) Write down the pathogen and transmission route of tuberculosis.\n(b) Explain which features of the alveoli help gas exchange, and why a pathogen can reach the lungs through the respiratory tract.", marks: "5 marks", answer: "(a) Pathogen: Mycobacterium tuberculosis (a bacterium); transmission route: droplets (coughing, sneezing).\n(b) The alveolar walls are thin, the surface area is large, the surface is moist and there is a rich network of capillaries, which suit gas exchange; however, if the mucus–cilia barrier of the respiratory tract (nose, trachea) is breached, the pathogen can reach the alveoli and cause infection." },
      { q: "Describe the pathway of the blood circulation, and explain why veins have valves but arteries do not.", marks: "5 marks", answer: "Pulmonary circulation: right ventricle → pulmonary artery → lungs → pulmonary vein → left atrium; systemic circulation: left ventricle → aorta → body → vena cavae → right atrium.\nThe blood pressure in veins is low and the flow slow, often against gravity on the return, so valves prevent backflow and ensure one-way flow to the heart; the pressure in arteries is high and driven by the heart, so valves are not needed." },
      { q: "Explain why breathing becomes faster and deeper after vigorous exercise, and state the relationship with the gas content of the blood.", marks: "5 marks", answer: "During vigorous exercise the muscles carry out more respiration and produce more carbon dioxide.\nThe rise in blood carbon dioxide and the fall in pH stimulate the chemoreceptors in the carotid body, aortic body and medulla oblongata.\nThe respiratory centre in the medulla sends more impulses to the respiratory muscles, making breathing faster and deeper.\nMore oxygen is taken in and more carbon dioxide expelled, supplying the muscles and maintaining the acid–base balance." },
      { q: "Compare blood, tissue fluid and lymph, and explain their relationships.", marks: "5 marks", answer: "Blood is in the blood vessels and contains blood cells and plasma; tissue fluid is in the intercellular spaces, formed from plasma leaking out at the arterial end of capillaries; lymph is formed from excess tissue fluid entering the lymphatic capillaries.\nMost tissue fluid returns to the blood by osmosis at the venous end; the remainder enters the lymphatic system and returns to the heart via the veins near the neck.\nThe three have similar major components (water, glucose, salts), but lymph contains no red blood cells." }
    ]
  },
  {
    bookId: "2A",
    name: "Book 2A",
    range: "Chapters 10–15",
    questions: [
      { q: "Compare the relationship between photosynthesis and respiration in gas exchange, and explain the significance of the compensation point.", marks: "6 marks", answer: "Photosynthesis takes in carbon dioxide and releases oxygen; respiration takes in oxygen and releases carbon dioxide.\nIn the daytime, when the light intensity is above the compensation point, the rate of photosynthesis is higher than respiration: net intake of carbon dioxide and net release of oxygen.\nCompensation point: the rate of photosynthesis equals the rate of respiration, with no net gas exchange.\nAt night only respiration occurs: net intake of oxygen and release of carbon dioxide.\nA plant must have photosynthesis exceeding respiration to have a net gain of food." },
      { q: "Explain the relationship between transpiration, translocation and support, using the wilting of a herbaceous plant as an example.", marks: "6 marks", answer: "Transpiration drives the upward transport of water in the xylem (transpiration pull), promoting water absorption by the roots; translocation transports sucrose in the phloem; support relies on turgor pressure (herbaceous) or lignified tissue (woody).\nIn hot weather a herbaceous plant transpires faster than it absorbs water, the parenchyma cells lose water, turgor pressure falls, support is lost and the plant wilts; woody plants are supported by the hardness of the xylem and are not affected." },
      { q: "Compare mitosis and meiosis, and explain their different significance to organisms.", marks: "6 marks", answer: "Mitosis involves one division, producing two daughter cells identical to the mother cell (diploid), used for growth, repair and asexual reproduction.\nMeiosis involves two divisions, producing four haploid gametes; fertilisation restores the diploid number; genetic variation is increased through independent assortment, crossing over and random fertilisation.\nMitosis maintains genetic stability; meiosis provides genetic diversity; together they support the continuation of life." },
      { q: "Explain the conditions for seed germination, and describe the changes in dry mass at the beginning of germination and after green leaves appear, with reasons.", marks: "5 marks", answer: "Conditions: water, a suitable temperature and oxygen.\nAt the beginning of germination: relying only on the food stored in the seed, respiration consumes organic matter, so the dry mass decreases.\nAfter green leaves appear: photosynthesis can occur, and when the rate of photosynthesis exceeds respiration, the dry mass increases.\nTherefore the dry mass first decreases and then increases." },
      { q: "Compare pollination and fertilisation, and explain the development of the flower parts after fertilisation.", marks: "5 marks", answer: "Pollination is the transfer of pollen from the anther to the stigma (by insects or wind); fertilisation is the fusion of the male gamete in the pollen tube with the female gamete in the ovule.\nAfter fertilisation: ovule → seed, integument → seed coat, ovary → fruit, ovary wall → fruit wall (pericarp); the zygote develops into an embryo.\nPollination is the prerequisite for fertilisation; both are important steps in the sexual reproduction of plants." }
    ]
  },
  {
    bookId: "2B",
    name: "Book 2B",
    range: "Chapters 16–19",
    questions: [
      { q: "Compare the nervous system and the endocrine system in coordinating the body, and explain how the two cooperate using blood glucose regulation as an example.", marks: "6 marks", answer: "The nervous system transmits messages quickly and briefly as electrical impulses (e.g. reflexes); the endocrine system transmits slowly and persistently through hormones transported by the blood.\nBlood glucose regulation: the pancreas (an endocrine gland) detects blood glucose and secretes insulin (lowering it) or glucagon (raising it), acting on the liver and body cells.\nThe nervous system can also regulate (e.g. the sympathetic nerves stimulate the adrenal gland to secrete adrenaline). The two cooperate to maintain homeostasis." },
      { q: "Describe how the eye and the ear convert stimuli into nerve impulses, and explain how the body compensates when a sense organ is damaged.", marks: "6 marks", answer: "Eye: light is refracted by the cornea and lens and focused on the retina; rod and cone cells convert light into nerve impulses, transmitted along the optic nerve to the brain.\nEar: sound waves vibrate the eardrum; the ossicles transmit the vibration to the oval window; the hair cells in the cochlea convert it into nerve impulses, transmitted along the auditory nerve to the brain.\nWhen a sense organ is damaged, the other senses (e.g. the hearing and touch of a blind person) and aids (glasses, hearing aids) can compensate." },
      { q: "Explain the difference between reflex actions and voluntary actions, and describe the components of a reflex arc.", marks: "5 marks", answer: "Reflex actions: rapid, involuntary, unconscious, not involving the brain (processed by the spinal cord or medulla), e.g. the knee-jerk reflex.\nVoluntary actions: initiated after thinking by the brain and under conscious control, e.g. writing.\nReflex arc: receptor → sensory neurone → centre → motor neurone → effector.\nReflex actions protect the body from harm and are faster than voluntary actions." },
      { q: "Describe how the kidneys regulate the water balance, and explain the role of ADH.", marks: "6 marks", answer: "The kidneys form urine through ultrafiltration and reabsorption.\nWhen short of water the blood water potential falls, detected by the osmoreceptors in the hypothalamus, which stimulate the pituitary to release more ADH.\nADH increases the permeability of the collecting duct to water, so more water is reabsorbed, the urine volume decreases and the urine is concentrated.\nWhen plenty of water is drunk the water potential rises, ADH decreases, and the urine volume increases.\nThe blood water potential is maintained stable through negative feedback." },
      { q: "Explain why both blood glucose regulation and water regulation are negative feedback mechanisms, and compare their receptors.", marks: "5 marks", answer: "Both operate on the pattern of 'deviation → correction → return to normal': blood glucose high → insulin lowers it; blood glucose low → glucagon raises it. Water: short of water → more ADH retains water; too much water → less ADH expels water.\nReceptor for blood glucose: the beta cells of the pancreas detect the blood glucose concentration.\nReceptor for water: the osmoreceptors in the hypothalamus detect the blood water potential.\nBoth bring the parameter back to the normal range." }
    ]
  },
  {
    bookId: "2C",
    name: "Book 2C",
    range: "Chapters 20–22",
    questions: [
      { q: "Describe the relationship between photosynthesis and respiration in energy and matter, and explain why the two are the basis of ecosystems.", marks: "6 marks", answer: "Photosynthesis converts light energy into chemical energy stored in glucose, absorbing carbon dioxide and releasing oxygen; respiration breaks down glucose to release energy (ATP), consuming oxygen and releasing carbon dioxide.\nThe two are reverse processes and form the core of the carbon and oxygen cycles.\nPhotosynthesis provides energy and food for the food chain (producers), and respiration provides energy for all organisms; therefore they are the basis of ecosystems." },
      { q: "Describe the shape of the pyramid of energy, and explain why the number of organisms at higher trophic levels is usually smaller.", marks: "5 marks", answer: "The pyramid of energy is an upright triangle (broad base, narrow top).\nWhen energy flows along a food chain, most is lost as heat (respiration), and only about 10% is transferred to the next level.\nThe energy available to higher trophic levels is less, so less biomass can be supported.\nTherefore the number of organisms at higher trophic levels is smaller and the length of food chains is limited." },
      { q: "Explain how human activities (burning fossil fuels, deforestation) affect the atmospheric carbon dioxide concentration in the carbon cycle.", marks: "5 marks", answer: "Burning fossil fuels releases the carbon stored over geological time into the atmosphere as carbon dioxide, increasing the atmospheric carbon dioxide.\nDeforestation reduces the ability of photosynthesis to absorb carbon dioxide, so atmospheric carbon dioxide increases.\nExcess carbon dioxide intensifies the greenhouse effect, causing global warming.\nTo mitigate this, the use of fossil fuels should be reduced, trees should be planted, and renewable energy used." },
      { q: "Describe the stages of aerobic respiration, and explain why the muscles carry out anaerobic respiration during vigorous exercise.", marks: "6 marks", answer: "Aerobic respiration: glycolysis (cytoplasm) → link reaction → Krebs cycle → oxidative phosphorylation (mitochondria), producing a large amount of ATP.\nDuring vigorous exercise the oxygen supply is insufficient for the energy needs of the muscles, so the muscles carry out anaerobic respiration (glycolysis), producing lactic acid and a small amount of ATP.\nThe accumulation of lactic acid causes muscle ache; after exercise the oxygen debt must be repaid (to break down the lactic acid).\nAnaerobic respiration releases far less energy than aerobic respiration." },
      { q: "Compare aerobic respiration and anaerobic respiration, and state the difference between the products of yeast and muscle cells under anaerobic conditions.", marks: "5 marks", answer: "Aerobic respiration: glucose is completely oxidised into carbon dioxide and water, releasing a large amount of energy, and requires oxygen.\nAnaerobic respiration: glucose is partially broken down, releasing a small amount of energy, and does not require oxygen.\nProducts of yeast anaerobic respiration: ethanol + carbon dioxide; products of muscle cell anaerobic respiration: lactic acid.\nBoth carry out glycolysis, but the subsequent pathways differ (alcoholic fermentation vs lactic acid fermentation)." }
    ]
  },
  {
    bookId: "3",
    name: "Book 3",
    range: "Chapters 23–25",
    questions: [
      { q: "Compare infectious and non-infectious diseases, and explain why vaccination is artificial active immunity.", marks: "6 marks", answer: "Infectious diseases are caused by pathogens and can spread between people (e.g. tuberculosis); non-infectious diseases are not caused by pathogens and cannot spread between people (e.g. diabetes, coronary heart disease).\nVaccines contain antigens, which stimulate the immune system to produce antibodies and memory cells; the antibodies are produced by the body's own immune system, so it is active immunity; and because the antigens are introduced artificially, it is artificial active immunity.\nVaccines provide long-lasting protection (memory cells)." },
      { q: "Explain how the body fights pathogens through non-specific and specific defence mechanisms, and compare the two.", marks: "6 marks", answer: "Non-specific: the skin and mucous membrane barrier, gastric acid and tears, phagocytosis, inflammation; effective against all pathogens, with no memory.\nSpecific: humoral immunity (B cells → plasma cells producing antibodies) and cell-mediated immunity (T cells); specific, producing memory cells.\nThe primary response is slow, and the secondary response is fast (memory).\nThe two work together: the non-specific defences block pathogens first, and the specific defences eliminate them precisely." },
      { q: "Explain how resistant bacteria arise through natural selection, and write down ways to reduce resistance.", marks: "6 marks", answer: "Genetic variation arises in the bacterial population through mutation, and some bacteria are resistant.\nAntibiotics kill the non-resistant bacteria, and the resistant bacteria survive and reproduce, passing the resistance gene to their offspring.\nAfter several generations the proportion of resistant bacteria rises.\nWays to reduce resistance: use antibiotics only when needed, complete the whole course, use narrow-spectrum antibiotics, avoid adding antibiotics to animal feed, develop new drugs." },
      { q: "Compare active immunity and passive immunity, giving two examples of each.", marks: "5 marks", answer: "Active immunity: the body's own immune system produces antibodies; long-lasting; natural (recovery from illness), artificial (vaccination).\nPassive immunity: antibodies are introduced from outside; short-lived; natural (from the mother via the placenta/breast milk), artificial (injection of antiserum).\nActive immunity produces memory cells and long-lasting immunity; passive immunity acts immediately but is short-lived and has no memory." },
      { q: "Explain why smoking increases the risk of non-infectious diseases (lung cancer, coronary heart disease), and write down two suggestions for quitting smoking.", marks: "5 marks", answer: "Tobacco contains carcinogens (tar), which damage the DNA of lung cells and increase the risk of lung cancer.\nNicotine constricts blood vessels, speeds up the heart and increases platelet stickiness, and carbon monoxide reduces the oxygen-carrying capacity of the blood, increasing the risk of atherosclerosis and coronary heart disease.\nSuggestions for quitting: seek professional counselling and medication, reduce gradually, use exercise to distract, support from family and friends (any two)." }
    ]
  },
  {
    bookId: "4",
    name: "Book 4",
    range: "Chapters 26–31",
    questions: [
      { q: "Describe the processes of DNA replication, transcription and translation, and explain how the three together achieve 'genes determine traits'.", marks: "7 marks", answer: "DNA replication: the double helix unwinds, complementary pairing occurs, and DNA polymerase synthesises the new strand (semiconservative).\nTranscription: mRNA is synthesised from the DNA template (RNA polymerase).\nTranslation: on the ribosome, tRNA carries amino acids and codons pair, synthesising a polypeptide.\nThe base sequence of a gene determines the mRNA sequence, which in turn determines the amino acid sequence of the protein (polypeptide), and the protein determines the trait.\nTherefore genes determine traits." },
      { q: "Explain Mendel's law of segregation and law of independent assortment, using tall and dwarf pea plants as an example.", marks: "5 marks", answer: "Law of segregation: when gametes form, the pair of alleles separates and each gamete contains only one (e.g. Tt produces T and t gametes).\nLaw of independent assortment: the alleles of different genes segregate and combine independently (genes on different chromosomes).\nTT × tt → F1 all Tt (tall); F1 self-cross → F2 tall : dwarf = 3:1.\nThis explains the 3:1 ratio of monohybrid inheritance." },
      { q: "Explain the types of gene mutations and their effects, using sickle cell anaemia as an example.", marks: "6 marks", answer: "Types of gene mutation: substitution (changes one codon; the effect can be large or small), insertion/deletion (frameshift mutation; large effect).\nSickle cell anaemia: one base T in the beta-globin gene is substituted by A, changing one amino acid.\nThe altered haemoglobin makes red blood cells sickle-shaped, reducing the oxygen-carrying capacity and easily blocking blood vessels.\nThis shows that a single base substitution can cause a serious disease." },
      { q: "Describe the steps of recombinant DNA technology, and explain why bacteria are suitable for producing human proteins.", marks: "6 marks", answer: "Steps: obtain the target gene (human insulin gene) → cut the gene and the plasmid with restriction enzymes → join them with DNA ligase to form a recombinant plasmid → introduce it into bacteria → culture to produce and purify.\nBacteria are suitable: they reproduce quickly, can be cultured in large quantities, have a low cost, can express human proteins, and can be selected with antibiotic resistance markers.\nTherefore bacteria can be used to produce human insulin in large quantities." },
      { q: "Explain how natural selection leads to evolution, using industrial melanism or resistant bacteria as an example.", marks: "5 marks", answer: "Genetic variation exists in the population.\nEnvironmental change (pollution, antibiotics) allows individuals with favourable traits to survive and reproduce (survival of the fittest).\nThe favourable genes are passed to the offspring, and the gene frequencies of the population change.\nExample: industrial melanism — dark moths are less easily caught on polluted tree trunks, survive and reproduce, so the proportion of dark moths rises; or resistant bacteria — antibiotics select the resistant bacteria.\nA change in the gene frequencies of a population is evolution." }
    ]
  },
  {
    bookId: "5",
    name: "Book 5",
    range: "Chapters 32–34",
    questions: [
      { q: "Compare body temperature regulation and water regulation, and explain how both maintain homeostasis through negative feedback.", marks: "6 marks", answer: "Body temperature: the hypothalamus detects the blood temperature; when hot → heat loss (vasodilation, sweating), when cold → heat production and retention (vasoconstriction, shivering, thyroxine).\nWater: the osmoreceptors in the hypothalamus detect the water potential; when short of water → more ADH retains water, when there is plenty of water → less ADH expels water.\nBoth detect the deviation and make the opposite response to bring the parameter back to normal, i.e. negative feedback.\nThe two together keep the internal environment stable." },
      { q: "Explain the transport mechanisms of oxygen and carbon dioxide between the blood and the tissues, and the role of haemoglobin.", marks: "6 marks", answer: "Oxygen: in the lungs the oxygen partial pressure is high, so oxygen combines with haemoglobin to form oxyhaemoglobin; in the tissues the oxygen partial pressure is low, so oxygen is released.\nCarbon dioxide: carbon dioxide produced in the tissues, a small part dissolves in the plasma, and most reacts with water in the red blood cells (catalysed by carbonic anhydrase) to form carbonic acid, which dissociates into hydrogencarbonate ions for transport; a small part combines with haemoglobin.\nHaemoglobin is the main carrier of oxygen and also participates in the transport of carbon dioxide." },
      { q: "Explain why the blood carbon dioxide concentration is the main regulating factor of breathing, and describe its regulatory pathway.", marks: "5 marks", answer: "The carbon dioxide concentration reflects the metabolic activity and acid–base state, and is the most sensitive signal for ventilation.\nCarbon dioxide rises → the blood pH falls → the chemoreceptors in the carotid body, aortic body and medulla oblongata detect it → stimulate the respiratory centre in the medulla → breathing becomes faster and deeper → more carbon dioxide is expelled → the pH returns.\nTherefore carbon dioxide (through pH) is the main regulating factor of breathing; the oxygen concentration is secondary." },
      { q: "Describe the coordinated responses of the cardiovascular and respiratory systems during exercise, and explain their importance.", marks: "6 marks", answer: "During exercise the muscles need more energy and produce more carbon dioxide.\nThe sympathetic nerves and adrenaline make the heart beat faster and contract more strongly, so the cardiac output increases; breathing becomes faster and deeper, so ventilation increases.\nThe skin blood vessels dilate to lose heat.\nThis supplies more oxygen and glucose to the muscles and speeds up the removal of carbon dioxide and lactic acid, sustaining performance.\nAfter exercise the breathing rate stays higher to repay the oxygen debt." },
      { q: "Explain why the body needs more oxygen at high altitude or during vigorous exercise, and describe how the body adapts.", marks: "5 marks", answer: "At high altitude the oxygen partial pressure of the air is low, so the blood oxygen is low; during vigorous exercise the muscles carry out vigorous respiration and need a lot of oxygen.\nAdaptation: at high altitude → the kidneys secrete erythropoietin, increasing red blood cells and haemoglobin to raise the oxygen-carrying capacity; breathing quickens.\nDuring vigorous exercise → the heart rate and breathing rate increase, supplying more oxygen; training strengthens the cardiorespiratory function.\nLong-term training raises the maximum oxygen uptake and improves performance." }
    ]
  },
  {
    bookId: "6",
    name: "Book 6",
    range: "Chapters 35–37",
    questions: [
      { q: "Describe the hormonal regulation of the menstrual cycle, and explain how the contraceptive pill uses hormones to suppress ovulation.", marks: "6 marks", answer: "FSH stimulates follicle development and the secretion of oestrogen; oestrogen thickens the lining, and its pre-ovulatory peak positively feeds back to stimulate an LH surge that triggers ovulation; after ovulation the corpus luteum secretes progesterone to maintain the lining; high oestrogen and progesterone negatively feed back to inhibit FSH/LH.\nThe contraceptive pill contains synthetic oestrogen and progesterone, maintaining high levels that negatively feed back to inhibit FSH and LH, so follicles do not develop and ovulation does not occur, preventing pregnancy." },
      { q: "Compare the types of pollution caused by human activities (air, water, land), giving one example and one effect of each.", marks: "6 marks", answer: "Air pollution: burning fossil fuels releases sulphur dioxide, nitrogen oxides and suspended particulates, causing acid rain and respiratory diseases.\nWater pollution: domestic sewage (pathogens), industrial wastewater (heavy metals), eutrophication, causing algal blooms and fish death.\nLand pollution: heavy metals, pesticides and solid waste (landfill leachate), polluting the soil and groundwater.\nEach type of pollution damages the ecology and human health and needs control." },
      { q: "Explain the causes, effects and mitigation of global warming.", marks: "6 marks", answer: "Causes: burning fossil fuels increases greenhouse gases such as carbon dioxide, which trap infrared radiation and raise the atmospheric temperature.\nEffects: rising sea levels, abnormal weather, the spread of infectious diseases, decline of biodiversity.\nMitigation: use renewable energy, save energy and reduce emissions, plant trees, reduce private car use, international cooperation (e.g. the Paris Agreement).\nEveryone can contribute by reducing their carbon footprint." },
      { q: "Describe the process of sewage treatment, and explain why the treated water must be disinfected before discharge.", marks: "5 marks", answer: "Primary treatment: screening and settling remove solids. Secondary treatment: micro-organisms break down organic matter (nitrification, denitrification). Tertiary treatment: nutrients and suspended solids are removed.\nDisinfection (e.g. chlorination) kills pathogens, preventing the spread of water-borne diseases.\nIf the water is discharged without disinfection, the pathogens pollute the water bodies and endanger health.\nThe treated water must meet quality standards before it is discharged into water bodies." },
      { q: "Explain the methods of conserving biodiversity (in-situ, ex-situ, legislation, sustainable development), and the role of individuals.", marks: "6 marks", answer: "In-situ conservation: setting up country parks, marine parks and reserves, preserving complete ecosystems.\nEx-situ conservation: breeding in zoos, seed banks, botanical gardens.\nLegislation: CITES regulates the trade in endangered species, anti-poaching laws.\nSustainable development: balancing the economy and the environment, sustainable fisheries, organic farming.\nIndividuals: reduce waste, support recycling, do not buy products made from endangered species, protect natural habitats, take part in environmental actions." }
    ]
  }
];
