// longQuestions2.en.js
// HKDSE Biology — Long questions part 2 (Topics 14–25) — English (UK) version
// Loaded when the app language is English (UK). Structure matches longQuestions2.js (zh-HK).
// Each chapter has 15 long questions with model answers (question and answer only, no marking).

const LQ2_EN = [
  {
    topicNo: 14,
    name: "Reproduction in Humans",
    questions: [
      { q: "Why must the fetus's blood be separated from the mother's blood? Give two reasons.", marks: "3 marks", answer: "To avoid the formation of blood clots when the bloods are incompatible.\nTo prevent some pathogens / toxins in the mother's blood from entering the fetus directly.\nTo avoid the high blood pressure of the mother's blood bursting the fetus's blood vessels. (any two)" },
      { q: "A woman uses the 'safe period' method of contraception, measuring her body temperature every morning. Explain why this method is not reliable and cannot predict the whole fertile period.", marks: "4 marks", answer: "Body temperature rises suddenly at ovulation, so this method can only tell when ovulation has occurred.\nBut the fertile period before ovulation (sperm survive for several days, and the date of ovulation may vary) cannot be predicted.\nEggs and sperm can survive in the reproductive tract for several days, so the fertile period spans the days before and after ovulation.\nTherefore the 'safe period' can only predict part of the fertile period and is not reliable." },
      { q: "Describe the functions of the parts of the male reproductive system (testis, epididymis, seminal vesicles/prostate gland, sperm duct, urethra).", marks: "5 marks", answer: "Testis: the seminiferous tubules produce sperm; it also produces the male sex hormone (testosterone).\nEpididymis: temporarily stores sperm and allows them to mature.\nSeminal vesicles / prostate gland: secrete fluid that mixes with sperm to form semen, activating and providing nutrients to the sperm, and neutralising the acidity of the vagina.\nSperm duct: carries the sperm out.\nUrethra: the passage for semen and urine to leave the body." },
      { q: "Describe the functions of the parts of the female reproductive system, and state where fertilisation takes place.", marks: "5 marks", answer: "Ovary: produces eggs and female sex hormones (oestrogen, progesterone).\nOviduct (fallopian tube): moves the egg towards the uterus by cilia; it is where fertilisation takes place.\nUterus: protects the embryo and allows implantation and development.\nVagina: the birth canal and the passage for sperm entry.\nFertilisation takes place in the oviduct: the sperm nucleus fuses with the egg nucleus to form a zygote." },
      { q: "Describe the functions of the placenta and the amniotic fluid, and explain the direction of blood flow in the umbilical vessels.", marks: "5 marks", answer: "Placenta: allows the exchange of substances between the embryo and the mother (oxygen, nutrients, antibodies, wastes), but their bloods do not mix.\nAmniotic fluid: protects the fetus from mechanical injury, prevents drying, gives the embryo room to move, and provides a stable environment.\nUmbilical cord: contains two umbilical arteries (carrying the fetus's deoxygenated blood to the placenta) and one umbilical vein (carrying oxygenated blood to the fetus)." },
      { q: "Explain how oral contraceptive pills suppress ovulation.", marks: "4 marks", answer: "Oral contraceptive pills contain synthetic oestrogen and progesterone.\nThe high levels of oestrogen and progesterone exert negative feedback on the pituitary, suppressing the secretion of FSH and LH.\nWith insufficient FSH, follicles cannot develop; with insufficient LH, ovulation cannot occur.\nNo egg is released, so sperm cannot meet an egg and fertilisation cannot occur." },
      { q: "Compare monozygotic and dizygotic twins in terms of genetics.", marks: "3 marks", answer: "Monozygotic (identical) twins develop from one zygote that splits, so they are genetically identical.\nDizygotic (fraternal) twins develop from two different eggs fertilised separately, so they are genetically as similar as ordinary siblings, not identical." },
      { q: "Write down three contraceptive methods and their principles.", marks: "5 marks", answer: "1. Condom / diaphragm: barrier method, preventing sperm from meeting the egg.\n2. Oral contraceptive pill: suppresses ovulation.\n3. Intrauterine device (IUD): prevents the fertilised egg from implanting in the uterine lining.\n4. Vasectomy / tubal ligation: surgical method preventing sperm and egg from meeting (any three with the principle)." },
      { q: "A woman ovulates on day 14 of her menstrual cycle.\n(a) Write down the event in the ovary at ovulation.\n(b) If the egg is not fertilised, what happens to the corpus luteum and the uterine lining?", marks: "4 marks", answer: "(a) A mature follicle ruptures and releases an egg (ovulation).\n(b) The corpus luteum degenerates, and the levels of oestrogen and progesterone fall; the uterine lining sheds together with blood, forming menstruation." },
      { q: "Describe the process by which an egg travels from release to fertilisation, including the mechanism of its movement.", marks: "4 marks", answer: "After ovulation, the egg enters the oviduct.\nThe beating of the cilia on the inner wall of the oviduct and the peristalsis of its wall move the egg towards the uterus.\nIf sperm meet the egg in the oviduct, the sperm nucleus fuses with the egg nucleus to form a zygote (fertilisation).\nThe zygote continues to divide and moves to the uterus for implantation." },
      { q: "Explain why the testes are located in the scrotum outside the body.", marks: "3 marks", answer: "Sperm formation requires a temperature slightly lower than body temperature; the scrotum is outside the body, so its temperature is lower, which helps sperm form and develop normally." },
      { q: "Write down the components of semen and explain the function of each.", marks: "4 marks", answer: "Semen consists of sperm and glandular secretions.\nSperm: carry the genetic material to fuse with the egg.\nThe fluid components (secreted by the seminal vesicles and prostate gland): provide nutrients to the sperm, activate the sperm, and neutralise the acidity of the vagina, increasing the survival and motility of the sperm." },
      { q: "Explain why a woman can still secrete progesterone to maintain the uterine lining during pregnancy even though the corpus luteum would degenerate.", marks: "4 marks", answer: "After fertilisation, the embryo secretes human chorionic gonadotrophin (hCG), which prevents the corpus luteum from degenerating.\nThe corpus luteum continues to secrete oestrogen and progesterone to maintain the thickness of the uterine lining.\nLater, the placenta takes over the secretion of progesterone and continues to maintain the pregnancy." },
      { q: "Describe the changes and roles of oestrogen, progesterone, FSH and LH in the menstrual cycle.", marks: "6 marks", answer: "Before ovulation: FSH stimulates follicle development; the follicle secretes oestrogen, which thickens the uterine lining; the oestrogen peak stimulates a surge of LH by positive feedback.\nOvulation (about day 14): the LH surge triggers ovulation.\nAfter ovulation: the corpus luteum secretes oestrogen and progesterone; progesterone maintains the lining and increases its blood supply; the high levels of oestrogen and progesterone inhibit FSH and LH (negative feedback), preventing the development of another follicle.\nIf not fertilised, the corpus luteum degenerates, the hormones fall, and the lining sheds to form menstruation." },
      { q: "Explain why the oestrogen level peaks before ovulation, and describe its relationship with LH.", marks: "4 marks", answer: "During follicle development the follicle secretes large amounts of oestrogen, which peaks before ovulation.\nThe high oestrogen level exerts positive feedback on the pituitary, stimulating a surge of LH (the LH peak).\nThe LH surge triggers ovulation, causing the egg to be released from the mature follicle." }
    ]
  },
  {
    topicNo: 15,
    name: "Growth and Development",
    questions: [
      { q: "Explain why the dry mass of a seedling decreases at the beginning of germination, but starts to increase after green leaves appear.", marks: "5 marks", answer: "At the beginning of germination, the seedling has not yet grown green leaves and can only rely on the food stored in the seed.\nThe stored starch is broken down into sugars by amylase and used up by respiration to provide energy, so the dry mass decreases.\nAfter green leaves appear, the seedling can carry out photosynthesis.\nWhen the rate of photosynthesis (food production) exceeds the rate of respiration (food consumption), there is a net gain of organic matter.\nTherefore the dry mass starts to increase." },
      { q: "Compare measuring the 'fresh mass' and 'dry mass' of plants as growth indicators, and explain why dry mass is more accurate.", marks: "5 marks", answer: "Fresh mass includes water and fluctuates with the water content, so it cannot accurately reflect the increase in organic matter.\nDry mass is the mass after all water is removed and reflects the actual biomass (organic matter).\nMeasuring dry mass requires drying the sample to a constant mass (about 100°C), which is time-consuming and destroys the sample.\nTherefore, to measure plant growth accurately, dry mass should be measured rather than fresh mass." },
      { q: "Write down the definitions of 'growth' and 'development', giving one example of each.", marks: "4 marks", answer: "Growth is a permanent and irreversible increase in dry mass and volume, through cell division and cell enlargement, e.g. a seedling growing taller.\nDevelopment is the process of increasing complexity, involving cell differentiation/specialisation, e.g. a zygote developing into an individual with many tissues, a bud differentiating into a flower." },
      { q: "Write down the conditions required for seed germination, and explain the role of each condition.", marks: "5 marks", answer: "Water: makes the seed swell and the enzymes active, starting metabolism.\nOxygen: for respiration, releasing energy for germination and growth.\nA suitable temperature: allows the enzymes to work at their optimum.\n(Light is not essential; most seeds can germinate in the dark.)" },
      { q: "Explain the roles of the plumule, radicle and cotyledons in seed germination.", marks: "4 marks", answer: "The plumule develops into the stem and leaves (the aerial part).\nThe radicle breaks through the seed coat first, developing into the root, absorbing water and anchoring the plant.\nThe cotyledons contain food reserves to support the growth of the embryo; before green leaves appear, the seedling is nourished by the cotyledons." },
      { q: "Write down where primary growth and secondary growth occur in plants and their functions.", marks: "4 marks", answer: "Primary growth: occurs at the apical meristems at the root tip and shoot tip, responsible for elongation.\nSecondary growth: occurs at the lateral meristem (vascular cambium), responsible for thickening.\nThe root tip has three zones: the zone of cell division, the zone of elongation (cells absorb water and enlarge, making the root/stem elongate), and the zone of differentiation." },
      { q: "Describe the five stages of human growth, and state the two stages with the highest growth rate.", marks: "4 marks", answer: "The five stages: fetal, infancy, childhood, adolescence and adulthood.\nThe infancy and adolescence (puberty) stages have the highest growth rate.\nPuberty shows a growth spurt (rapid increase in height)." },
      { q: "Explain how the phototropism of plant shoots is caused by auxin.", marks: "5 marks", answer: "Unilateral light causes auxin to move from the illuminated side to the shaded side.\nA higher concentration of auxin promotes the growth of shoots.\nTherefore the shaded side of the shoot grows faster than the illuminated side.\nThe faster-growing side makes the shoot bend towards the light source.\nThis places the leaves in the best position to absorb the most sunlight for photosynthesis." },
      { q: "Explain the positive geotropism of roots and the negative geotropism of shoots.", marks: "3 marks", answer: "Under the influence of gravity, auxin accumulates on the lower side of both roots and shoots.\nShoots respond to auxin by promoting growth, so the lower side grows faster and the shoot bends upwards (negative geotropism).\nRoots respond to auxin by inhibiting growth, so the lower side grows more slowly and the root bends downwards (positive geotropism)." },
      { q: "A student measured the height and dry mass of a plant and found that the height kept increasing but the dry mass decreased at a certain stage. Explain.", marks: "4 marks", answer: "Height reflects elongation growth, which is caused by cells absorbing water and swelling, so it can keep increasing.\nDry mass reflects the net increase in organic matter; if respiration consumes more food than photosynthesis produces (e.g. on cloudy days, when leaves are shaded), the dry mass will decrease.\nTherefore the two indicators are not always consistent; dry mass should be used as the accurate measure of growth." },
      { q: "Explain why a seedling only grows green leaves after emerging from the soil, and the importance of this to the survival of the seedling.", marks: "4 marks", answer: "In the early stage the seedling grows using the nutrients stored in the seed and does not need photosynthesis.\nAfter emerging, green leaves grow and the seedling can carry out photosynthesis to make food, becoming autotrophic and no longer relying on the seed's nutrients.\nOnce the green leaves unfold, the rate of photosynthesis exceeds the rate of respiration, the dry mass increases, and the seedling can grow independently." },
      { q: "Write down the internal and external factors affecting plant growth, with two examples of each.", marks: "4 marks", answer: "Internal factors: plant hormones (e.g. auxin), genetic factors.\nExternal factors: light, water, temperature, mineral supply, etc.\nHormones and genes determine the pattern of growth; environmental factors affect the rate and direction of growth." },
      { q: "Explain why insects need to moult (shed their skin) in order to grow.", marks: "3 marks", answer: "Insects have a hard exoskeleton that cannot grow with the body;\nto grow, an insect must periodically shed its old exoskeleton (moult), exposing a softer new exoskeleton so the body can enlarge; the new exoskeleton then hardens." },
      { q: "Describe the stages of the life cycle of an insect with complete metamorphosis (e.g. a butterfly).", marks: "4 marks", answer: "Complete metamorphosis has four stages: egg → larva (e.g. caterpillar) → pupa → adult.\nThe larva and adult differ in form and habits; during the pupal stage internal reorganisation occurs, and finally the adult emerges." },
      { q: "Explain why dry mass, rather than fresh mass or volume, is the most accurate measure of plant growth.", marks: "4 marks", answer: "Dry mass reflects the actual increase in organic matter (biomass) in the organism and is not affected by the water content;\nfresh mass fluctuates with water content, and volume is affected by water and air spaces, so neither can accurately reflect the increase in organic matter.\nTherefore measuring dry mass gives the most accurate measure of growth." }
    ]
  },
  {
    topicNo: 16,
    name: "Stimuli, Receptors and Responses",
    questions: [
      { q: "Describe and explain the mechanism of phototropism of a plant shoot under unilateral light.", marks: "5 marks", answer: "Unilateral light causes auxin to move from the illuminated side to the shaded side.\nA higher concentration of auxin promotes the growth of shoots.\nTherefore the shaded side of the shoot grows faster than the illuminated side.\nThe faster-growing side makes the shoot bend towards the light source.\nThis places the leaves in the best position to absorb the most sunlight for photosynthesis." },
      { q: "A man saw an object he had seen before. With reference to the functional areas of the brain, explain how he recognised the object.", marks: "4 marks", answer: "Light enters the eye and forms an image on the retina; the photoreceptors generate nerve impulses.\nThe impulses travel along the optic nerve to the sensory area of the brain, producing vision.\nThe information is passed to the association area, which interprets it according to the memories stored from past experience.\nTherefore the man could recognise the object." },
      { q: "Describe the response of the pupil of the eye in bright light and in dim light, and explain its importance.", marks: "4 marks", answer: "In bright light: the circular muscles of the iris contract and the radial muscles relax, the pupil constricts, reducing the amount of light entering and protecting the retina.\nIn dim light: the circular muscles relax and the radial muscles contract, the pupil dilates, allowing more light to enter and reach the retina to produce a clearer image.\nThe pupil reflex is an involuntary reflex action." },
      { q: "Describe the accommodation of the lens when looking at a near object and a distant object.", marks: "4 marks", answer: "Looking at a near object: the ciliary muscles contract, the tension of the suspensory ligaments decreases, the lens becomes thicker (more convex), the refractive power increases, and the image is focused on the retina.\nLooking at a distant object: the ciliary muscles relax, the suspensory ligaments are pulled tight, the lens becomes thinner (flatter), and the refractive power decreases.\nBy changing the shape of the lens, images of objects at different distances are focused on the retina." },
      { q: "Compare rod cells and cone cells in terms of distribution and function.", marks: "4 marks", answer: "Rod cells: distributed in the periphery of the retina, sensitive to light, working in dim light, producing black-and-white vision, unable to distinguish colours.\nCone cells: concentrated mainly in the yellow spot, working in bright light, distinguishing colours, producing colour vision.\nThe yellow spot is the position of clearest vision (with the highest density of cone cells)." },
      { q: "Explain the cause and correction of short-sightedness (myopia).", marks: "4 marks", answer: "Cause of myopia: the eyeball is too long or the lens is too convex, so the image of a distant object is focused in front of the retina, making distant objects blurry.\nCorrection: use a concave lens, which diverges the light first so that the image moves back and is focused on the retina.\n(Long-sightedness is caused by an eyeball that is too short or a lens that is too thin, corrected with a convex lens.)" },
      { q: "Describe the process by which sound waves travel from the outer ear to the cochlea and are converted into nerve impulses.", marks: "4 marks", answer: "Sound waves travel through the auditory canal to the eardrum, causing it to vibrate.\nThe ossicles (malleus, incus, stapes) amplify the vibrations and transmit them to the oval window.\nThe vibrations are transmitted to the fluid in the cochlea.\nThe hair cells in the cochlea detect the vibrations and generate nerve impulses, which travel along the auditory nerve to the auditory centre of the brain, producing hearing." },
      { q: "Write down the functions of the semicircular canals and the Eustachian tube in the ear.", marks: "3 marks", answer: "Semicircular canals: detect rotation of the head and body balance (changes in position).\nEustachian tube: equalises the air pressure on the two sides of the eardrum, preventing the eardrum from being damaged by a pressure difference." },
      { q: "Write down the characteristics of reflex actions, and describe the components of a reflex arc.", marks: "5 marks", answer: "Characteristics of reflex actions: rapid, involuntary, unconscious responses to stimuli, not involving the brain (processed by the spinal cord or medulla oblongata).\nReflex arc: receptor → sensory neurone → central nervous system (spinal cord/medulla) → motor neurone → effector (e.g. muscle).\nExamples: withdrawing the hand on touching something hot, knee-jerk reflex." },
      { q: "Explain the importance of reflex actions to the survival of organisms, giving an example.", marks: "3 marks", answer: "Reflex actions enable organisms to respond rapidly to dangerous stimuli, protecting the body from harm, without the need for brain thinking, so the response is faster.\nFor example, the hand is withdrawn immediately when it touches something hot, avoiding a burn; blinking protects the eye." },
      { q: "Describe the function of receptors, and write down three types of receptors present in the skin.", marks: "3 marks", answer: "Function of receptors: converting stimuli into nerve impulses.\nReceptors in the skin: touch receptors, pain receptors, temperature receptors (cold/hot).\n(The skin has no light receptors.)" },
      { q: "Explain why objects look more colourful in bright light but colours are not obvious in dim light.", marks: "4 marks", answer: "Colour vision is the function of cone cells, which work properly only in bright light.\nIn bright light the cone cells are fully stimulated and can distinguish colours, so objects look colourful.\nIn dim light the cone cells are insensitive, and vision is mainly by rod cells (black-and-white), so colour discrimination decreases and colours are not obvious." },
      { q: "A student studied the response of plant roots to gravity.\n(a) Predict the direction of root growth.\n(b) Explain the significance of this response.", marks: "4 marks", answer: "(a) The root grows downwards (positive geotropism).\n(b) Growing downwards into the soil allows the root to absorb water and minerals and to anchor the plant, which is important for survival.\n(Under gravity, auxin accumulates on the lower side of the root, inhibiting growth on that side, so the root bends downwards.)" },
      { q: "Explain why the pupil dilates in the dark.", marks: "3 marks", answer: "In the dark the light is weak, so the circular muscles of the iris relax and the radial muscles contract, the pupil dilates, allowing more light to enter the eye and reach the retina, improving the ability to see in the dark and producing a clearer image." },
      { q: "Describe the difference between tropism and nastic movement in plants.", marks: "3 marks", answer: "Tropism: the direction of growth is determined by the direction of the stimulus (e.g. phototropism, geotropism); it is a slow growth response.\nNastic movement (e.g. the closing of the leaves of a sensitive plant): the direction of the response is not related to the direction of the stimulus; it is a relatively fast movement response." }
    ]
  },
  {
    topicNo: 17,
    name: "Coordination in Humans",
    questions: [
      { q: "Using a flow diagram, show the pathway of nerve transmission in 'the pupil constricting in bright light', including the types of neurones involved.", marks: "4 marks", answer: "Receptor (photoreceptors in the retina) → sensory neurone → central nervous system (brain / relay neurone) → motor neurone → effector (iris muscles).\nThe circular muscles of the iris contract, making the pupil constrict, reducing the amount of light entering the eye." },
      { q: "Describe how a nerve impulse crosses the neuromuscular junction and causes muscle contraction.", marks: "4 marks", answer: "The nerve impulse reaches the end of the axon, triggering the release of a neurotransmitter (chemical messenger) into the neuromuscular junction.\nThe neurotransmitter diffuses across the synapse.\nThe neurotransmitter binds to receptors on the muscle fibre membrane.\nAn electrical impulse is triggered in the muscle fibre, causing the muscle to contract." },
      { q: "Write down the components of the central nervous system and the peripheral nervous system, and describe the three main parts of a neurone.", marks: "4 marks", answer: "Central nervous system: the brain and the spinal cord.\nPeripheral nervous system: the cranial nerves and spinal nerves.\nA neurone has: a cell body (containing the nucleus), dendrites (conducting impulses towards the cell body), and an axon (conducting impulses away)." },
      { q: "Compare the nervous system and the endocrine system in transmitting messages (speed, duration, method of transmission).", marks: "4 marks", answer: "Nervous system: transmits electrical impulses along neurones and neurotransmitters across synapses; fast, short-lasting, and targeted at specific parts.\nEndocrine system: hormones transported by the blood to all parts of the body; slow, long-lasting, with a wider range of effects.\nThe two work together to coordinate the body." },
      { q: "Describe the structure of a synapse, and explain why transmission across a synapse is one-way.", marks: "4 marks", answer: "A synapse is the gap between the end of a neurone and the next neurone; the nerve ending contains vesicles of neurotransmitter.\nWhen an impulse arrives, neurotransmitter is released and diffuses across the synaptic gap to bind to receptors, stimulating the next neurone.\nAs the neurotransmitter is only released by the presynaptic membrane and receptors are only on the postsynaptic membrane, transmission is one-way.\nThe synapse also allows one neurone to communicate with many neurones." },
      { q: "Write down the functions of the cerebrum, cerebellum and medulla oblongata.", marks: "5 marks", answer: "Cerebrum: responsible for intelligence, thinking, memory and learning, and controlling voluntary actions; it is divided into the sensory, association and motor areas.\nCerebellum: coordinates skeletal muscle activities and maintains body balance.\nMedulla oblongata: controls involuntary actions such as breathing and heartbeat, and various reflexes (e.g. swallowing, coughing)." },
      { q: "Describe the regulation of blood glucose (the roles of insulin and glucagon).", marks: "5 marks", answer: "Blood glucose high → the pancreas secretes more insulin → the liver converts glucose into glycogen and body cells absorb more glucose → blood glucose falls.\nBlood glucose low → the pancreas secretes more glucagon → the liver converts glycogen into glucose → blood glucose rises.\nInsulin and glucagon are secreted by the pancreas and are regulated by negative feedback." },
      { q: "Explain why patients with diabetes mellitus (insufficient insulin) have high blood glucose.", marks: "4 marks", answer: "The function of insulin is to make the liver and body cells absorb glucose and to convert glucose into glycogen.\nWhen insulin is insufficient, cells absorb less glucose and less glycogen is synthesised.\nBlood glucose cannot be lowered effectively and stays at a high level.\nWhen blood glucose is too high, the excess glucose is excreted in the urine (glycosuria), so the urine may contain sugar." },
      { q: "Describe the role of adrenaline in an emergency, and explain its significance to the body.", marks: "4 marks", answer: "In an emergency the sympathetic nervous system stimulates the adrenal gland to secrete adrenaline.\nAdrenaline speeds up the heartbeat and breathing, raises blood glucose, and constricts some blood vessels (redirecting blood flow to the muscles).\nThis puts the body into a 'fight or flight' state, providing more energy and oxygen to deal with the emergency and improving responsiveness." },
      { q: "Write down the difference between endocrine glands and exocrine glands, giving two examples of each.", marks: "4 marks", answer: "Endocrine glands are ductless glands; hormones are secreted directly into the blood, e.g. the thyroid gland, pituitary gland, adrenal gland, and the islets of the pancreas.\nExocrine glands secrete their products through ducts to the body surface or body cavities, e.g. salivary glands, sweat glands, gastric glands.\n(The pancreas is both an exocrine and an endocrine gland.)" },
      { q: "Explain how hormones reach their target organs, and why hormones act only on specific targets.", marks: "4 marks", answer: "Hormones are secreted by endocrine glands into the blood and transported to all parts of the body.\nOnly cells with the corresponding receptors (the target organs) can respond to a particular hormone.\nDifferent cells have different receptors, so hormones are specific and act only on their target organs." },
      { q: "Describe the function of the spinal cord, and explain why injury to the spinal cord may cause paralysis.", marks: "4 marks", answer: "The spinal cord transmits nerve impulses between the brain and the body and acts as the centre for spinal reflexes (e.g. the knee-jerk reflex).\nInjury to the spinal cord interrupts the transmission of impulses between the brain and the body, so the parts below the injury lose sensation and voluntary motor control, causing paralysis." },
      { q: "A diabetic patient's blood glucose falls after injecting insulin. Explain how insulin lowers blood glucose, and why insulin is injected rather than taken orally.", marks: "5 marks", answer: "Insulin stimulates the body cells and liver cells to take up more glucose from the blood.\nIt stimulates the body cells to increase respiration, using up glucose.\nIt stimulates the liver/muscle cells to convert glucose into glycogen for storage.\nTherefore the blood glucose level falls.\nInsulin is a protein; if taken orally, it would be broken down by digestive enzymes and lose its effect, so it has to be injected." },
      { q: "Write down the actions of the sympathetic and parasympathetic nerves, giving one example of each.", marks: "4 marks", answer: "Sympathetic nerves: prepare the body for emergencies, speeding up the heartbeat, widening the airways, raising blood glucose and inhibiting digestion, e.g. the heartbeat quickens during exercise.\nParasympathetic nerves: allow the body to rest and recover, slowing the heartbeat and promoting digestion, e.g. digestive activities increase after a meal.\nThe two act antagonistically to coordinate the state of the body." },
      { q: "Describe the reflex arc of the knee-jerk reflex, and explain why it does not require the brain.", marks: "4 marks", answer: "Tapping the patellar tendon stimulates receptors → sensory neurone → spinal cord (centre) → motor neurone → contraction of the quadriceps, the leg kicks up.\nThe reflex arc is completed at the level of the spinal cord and does not need to be sent up to the brain, so the response is rapid and involuntary.\n(The brain may become aware of the reflex afterwards, but it does not start it.)" }
    ]
  },
  {
    topicNo: 18,
    name: "Movement in Humans",
    questions: [
      { q: "Outline how ligaments (A) and tendons (B) work together to allow a joint to move.", marks: "4 marks", answer: "Ligaments bind the bones together, preventing the bones from dislocating during movement.\nTendons attach muscles to bones and transmit the pulling force generated when the muscles contract.\nWhen a muscle contracts, it pulls the bone towards it through the tendon, moving the joint." },
      { q: "Explain why elderly people are more prone to fractures.", marks: "4 marks", answer: "The hardness of bone comes from inorganic components such as calcium salts, and its elasticity comes from organic components such as proteins.\nIn elderly people the protein (organic component) in the bone decreases, so the proportion of calcium salts is relatively higher.\nThe bone therefore becomes more brittle and less elastic.\nAs a result, it is more easily broken (fractured)." },
      { q: "Write down five functions of the skeleton.", marks: "5 marks", answer: "1. Supporting the body.\n2. Allowing movement (with muscles and joints).\n3. Protecting internal organs (e.g. the skull protects the brain, the rib cage protects the heart and lungs).\n4. Making blood cells (red bone marrow).\n5. Storing minerals (e.g. calcium) and fat." },
      { q: "Describe the structure of a joint, and write down the function of each structure (ligaments, articular cartilage, synovial fluid, joint capsule).", marks: "5 marks", answer: "Ligaments: connect bone to bone, preventing the bones from dislocating.\nArticular cartilage: covers the joint surfaces, reducing friction between bones.\nSynovial fluid: lubricates the joint, reducing friction.\nJoint capsule: surrounds the joint; its inner synovial membrane secretes synovial fluid.\n(Tendons: connect muscle to bone and transmit pulling force.)" },
      { q: "Compare hinge joints and ball-and-socket joints, giving two examples of each.", marks: "4 marks", answer: "Hinge joints: allow movement in only one plane (bending and straightening), e.g. the elbow joint and knee joint.\nBall-and-socket joints: allow movement in many planes, with the greatest range of movement, e.g. the shoulder joint and hip joint.\nIn a ball-and-socket joint, a ball-shaped head fits into a socket." },
      { q: "Explain how antagonistic muscles cause the bending and straightening of a limb, using the biceps and triceps as an example.", marks: "5 marks", answer: "Antagonistic muscles are pairs of muscles that act in opposite directions.\nBending the arm: the biceps (flexor) contracts and the triceps (extensor) relaxes, so the forearm bends upwards.\nStraightening the arm: the triceps contracts and the biceps relaxes, so the forearm straightens.\nMuscles can only contract (pull) and cannot push, so pairs of antagonistic muscles are needed to complete movements in both directions." },
      { q: "Describe the energy source required for muscle contraction, and the process of muscle contraction.", marks: "5 marks", answer: "The energy comes from respiration (ATP).\nProcess: a nerve impulse travels along a motor neurone to the end of the axon → releases a neurotransmitter → diffuses across the neuromuscular junction → stimulates the muscle fibre to generate an electrical impulse → the muscle contracts.\nATP is hydrolysed to release energy for the sliding of myofilaments (contraction)." },
      { q: "Explain why red bone marrow is very important to the body, and state the main locations of red bone marrow in adults.", marks: "4 marks", answer: "Red bone marrow makes blood cells (red blood cells, white blood cells and platelets), which are important for oxygen transport, immunity and blood clotting.\nIn adults, red bone marrow is mainly found in flat bones such as the sternum, ribs, pelvis and vertebrae.\n(Yellow bone marrow mainly stores fat.)" },
      { q: "Explain why exercise helps maintain bone health.", marks: "3 marks", answer: "Weight-bearing exercise applies stress to the bones, stimulating bone formation (bone cells become active) and increasing bone density;\nregular exercise also strengthens the muscles, protecting the joints and bones;\nlack of exercise causes bone loss and decreased bone density, increasing the risk of fractures." },
      { q: "Describe the components of bone, and explain how their proportions affect the properties of bone.", marks: "4 marks", answer: "Bone contains inorganic components (mainly calcium salts) and organic components (mainly proteins such as collagen).\nThe inorganic components provide hardness, and the organic components provide elasticity.\nIn young people there are more organic components, so the bone is more elastic and less likely to break; in old age the proportion of calcium salts is higher and protein is reduced, so the bone is more brittle and easily broken." },
      { q: "Write down the components of the axial skeleton and the appendicular skeleton of the human body.", marks: "4 marks", answer: "Axial skeleton: the skull, vertebral column and rib cage (sternum and ribs).\nAppendicular skeleton: the limb bones (upper and lower limbs), shoulder girdle (clavicle, scapula) and pelvic girdle (hip bones).\nThe axial skeleton protects the central organs, and the appendicular skeleton supports movement." },
      { q: "Explain the role of articular cartilage and synovial fluid in reducing friction.", marks: "3 marks", answer: "Articular cartilage covers the ends of the bones and has a smooth surface, reducing friction between bones.\nSynovial fluid is secreted by the synovial membrane and lubricates the joint surfaces, further reducing friction and wear so that the joint moves smoothly." },
      { q: "When a weightlifter lifts a barbell, what are the states of the biceps and triceps? Explain.", marks: "4 marks", answer: "When lifting a weight (bending the forearm), the biceps contracts and the triceps relaxes.\nThe biceps contraction pulls the forearm upwards through the tendon; the triceps relaxes and does not resist.\n(When lowering/straightening, the triceps contracts and the biceps relaxes.)" },
      { q: "Describe the significance of the S-shape of the vertebral column to the body.", marks: "3 marks", answer: "The S-shape of the vertebral column absorbs shock during movement, reducing vibration to the brain and protecting it;\nthe S-shape also helps maintain the centre of gravity and balance, supporting the upright posture." },
      { q: "Write down the differences between skeletal muscle, smooth muscle and cardiac muscle.", marks: "4 marks", answer: "Skeletal muscle: attached to bones, under voluntary control, striated, innervated by motor neurones, e.g. the biceps.\nSmooth muscle: found in the walls of internal organs (alimentary canal, blood vessels), not under voluntary control, non-striated.\nCardiac muscle: found only in the heart, not under voluntary control, striated, able to contract rhythmically and automatically." }
    ]
  },
  {
    topicNo: 19,
    name: "Homeostasis",
    questions: [
      { q: "Siu Tung has diabetes mellitus. Explain which type of diabetes he has, and explain the difference in his blood glucose response after drinking a glucose solution compared with a healthy person.", marks: "6 marks", answer: "Siu Tung has insulin-dependent (type 1) diabetes.\nEven when the blood glucose is high, his blood insulin level is lower than that of a healthy person, showing that he cannot produce a normal amount of insulin.\nWithout enough insulin, his efficiency of absorbing glucose from the blood is lower.\nTherefore after taking glucose, his blood glucose concentration rises to a higher level.\nAnd it stays at a high level for a longer time.\nTreatment: injecting insulin." },
      { q: "Describe how insulin lowers the blood glucose level.", marks: "4 marks", answer: "It stimulates the body cells and liver cells to take up more glucose from the blood.\nIt stimulates the body cells to increase respiration, using up glucose.\nIt stimulates the liver/muscle cells to convert glucose into glycogen for storage.\nTherefore the blood glucose level falls." },
      { q: "Explain the meaning of 'homeostasis', and give three examples regulated by homeostasis.", marks: "4 marks", answer: "Homeostasis is maintaining the internal environment of the body in a relatively stable state, so that cells can work under optimal conditions.\nExamples: regulation of blood glucose, regulation of body temperature, regulation of water (water potential) content, regulation of gas content in the blood.\nThese are maintained mainly by negative feedback mechanisms." },
      { q: "Explain the negative feedback mechanism, illustrating with the regulation of blood glucose.", marks: "5 marks", answer: "Negative feedback: when a parameter deviates from its normal value, the body produces an opposite response to bring the parameter back to normal.\nBlood glucose high: the pancreas secretes more insulin, glucose is converted into glycogen, and blood glucose falls.\nBlood glucose low: the pancreas secretes more glucagon, glycogen is converted into glucose, and blood glucose rises.\nAfter the deviation is corrected, the hormone secretion returns to normal, forming homeostatic regulation." },
      { q: "Write down the causes and treatment of type 1 and type 2 diabetes.", marks: "5 marks", answer: "Type 1 (insulin-dependent): the beta cells of the pancreas are destroyed and cannot make or make only a little insulin; it usually develops in young people; insulin must be injected.\nType 2 (non-insulin-dependent): the target cells do not respond to insulin (insulin resistance); it is associated with unhealthy lifestyles such as obesity and lack of exercise; it can be controlled by diet and exercise, and medication may be needed in severe cases." },
      { q: "Explain why diabetic patients urinate more frequently and their urine contains sugar.", marks: "4 marks", answer: "Diabetic patients have high blood glucose, so the concentration of glucose in the glomerular filtrate is also high.\nThe renal tubules cannot reabsorb all the glucose, so some glucose remains in the filtrate.\nThe glucose in the filtrate lowers its water potential, reducing the reabsorption of water.\nTherefore a large amount of dilute urine is produced, increasing urine output and frequency, and the urine contains sugar." },
      { q: "Describe the location of the body temperature regulating centre and the role of the skin in losing and retaining heat.", marks: "5 marks", answer: "The body temperature regulating centre is in the hypothalamus.\nLosing heat: the skin blood vessels dilate (increasing blood flow to lose heat) and the sweat glands increase sweating (evaporation carries away heat).\nRetaining heat: the skin blood vessels constrict (reducing heat loss), the arrector pili muscles contract, and sweating decreases; a long-term response is that thyroxine increases the metabolic rate to produce heat.\n(Shivering of muscles produces heat when cold.)" },
      { q: "Explain why the skin blood vessels dilate and sweating increases in hot weather, but the opposite happens in cold weather.", marks: "5 marks", answer: "Hot weather: the hypothalamus detects the rise in blood temperature, stimulates the heat-loss centre, the small arteries in the skin dilate so more blood flows near the skin surface to lose heat; the sweat glands increase sweating, and the evaporation of sweat carries away heat.\nCold weather: the hypothalamus stimulates the heat-producing centre, the skin small arteries constrict, reducing skin blood flow to reduce heat loss; sweating decreases; the muscles shiver to produce heat.\nThese responses keep the body temperature within the normal range (negative feedback)." },
      { q: "Write down the excretory function of the kidneys, and describe the formation of urine (ultrafiltration and reabsorption).", marks: "5 marks", answer: "The kidneys excrete urea, excess water and salts.\nUltrafiltration: the high blood pressure in the glomerulus forces water and small molecules (glucose, amino acids, salts, urea) out of the blood into Bowman's capsule, forming the glomerular filtrate (which does not contain blood cells and large protein molecules).\nReabsorption: the proximal convoluted tubule reabsorbs glucose, amino acids and most salts; water is reabsorbed by osmosis; some urea diffuses back into the blood.\nNormal urine does not contain protein or glucose." },
      { q: "Explain why normal urine does not contain protein and glucose.", marks: "4 marks", answer: "Protein molecules are too large to pass through the glomerular filtration membrane, so they stay in the blood and are absent from urine.\nGlucose molecules are small enough to be filtered out, but the renal tubules reabsorb all glucose by active transport, so normal urine does not contain glucose.\nIf protein appears in the urine → the glomeruli are damaged; if glucose appears → blood glucose is too high (diabetes)." },
      { q: "Describe how the thirst mechanism helps maintain the water balance of the body.", marks: "4 marks", answer: "When the body is short of water, the water potential of the blood falls, detected by the osmoreceptors in the hypothalamus.\nThe hypothalamus stimulates the pituitary to release more ADH, increasing water reabsorption and reducing urine output.\nAt the same time a thirst sensation is produced, prompting drinking to replenish water.\nTogether these restore the blood water potential to normal." },
      { q: "Explain why sweating helps regulate body temperature, and why the efficiency of heat loss by sweating is lower in humid weather.", marks: "4 marks", answer: "Sweat is mainly water; when sweat evaporates it carries away heat from the skin, cooling the body.\nIn humid weather the humidity of the air is high, so sweat evaporates slowly and less heat is carried away; the efficiency of heat loss is low, so people feel hotter.\n(Low wind speed and high humidity both slow evaporation.)" },
      { q: "Write down the organs involved in homeostasis (e.g. pancreas, liver, kidneys, skin, lungs) and their roles.", marks: "5 marks", answer: "Pancreas: secretes insulin and glucagon to regulate blood glucose.\nLiver: converts glucose into glycogen or breaks down glycogen, regulating blood glucose.\nKidneys: excrete urea and excess water and salts, regulating water balance.\nSkin: regulates body temperature through sweating and regulating blood flow.\nLungs: excrete carbon dioxide, regulating the gas content of the blood." },
      { q: "Explain why the regulation of blood glucose and body temperature are both negative feedback mechanisms.", marks: "4 marks", answer: "Both operate on the pattern of 'deviation → correction → return to normal': when a parameter deviates from normal, an opposite response is produced to bring it back.\nBlood glucose high → insulin lowers it; blood glucose low → glucagon raises it.\nBody temperature high → heat loss; body temperature low → heat production and heat retention.\nThe response stops after the deviation is corrected, so both are negative feedback." },
      { q: "A diabetic patient mistakenly injected too much insulin. Predict the change in his blood glucose level and the possible symptoms, and explain.", marks: "4 marks", answer: "Excess insulin makes the cells absorb a lot of glucose and the liver convert a lot of glucose into glycogen, so the blood glucose drops sharply (hypoglycaemia).\nSymptoms: dizziness, weakness, fainting, sweating, etc. (the brain lacks glucose).\nTreatment: take sugar immediately (e.g. drink sugar water) to raise the blood glucose. Insulin regulation is negative feedback, but an injected excess goes beyond the normal regulatory range." }
    ]
  },
  {
    topicNo: 20,
    name: "Ecosystem",
    questions: [
      { q: "Describe the main processes in the nitrogen cycle (nitrogen fixation, ammonification, nitrification, denitrification).", marks: "6 marks", answer: "Nitrogen fixation: nitrogen-fixing bacteria convert atmospheric nitrogen into ammonia / nitrogen compounds usable by plants.\nAmmonification: decomposers convert the organic nitrogen in dead organisms into ammonium compounds.\nNitrification: nitrifying bacteria convert ammonium into nitrites and nitrates.\nNitrates are absorbed by producers to synthesise organic compounds such as proteins.\nDenitrification: denitrifying bacteria convert nitrates into nitrogen gas, returning it to the atmosphere." },
      { q: "In a marine ecosystem the food chain is 'phytoplankton → fish → shark'. Draw its pyramid of numbers and explain its shape.", marks: "5 marks", answer: "The pyramid is an upright triangle: a large number of phytoplankton at the base, fish in the middle, and a few sharks at the top.\nExplanation: not all the energy of a lower trophic level is transferred to the higher level; energy is lost along the food chain through respiration.\nThe organisms of lower trophic levels are smaller in size.\nTherefore more organisms of lower trophic levels are needed to support the higher trophic levels." },
      { q: "Write down the components of an ecosystem, and explain the difference between biotic and abiotic factors.", marks: "4 marks", answer: "An ecosystem consists of a community of organisms interacting with its non-living environment.\nBiotic factors: the relationships between organisms, such as reproduction, predation, competition and parasitism.\nAbiotic factors: light, temperature, rainfall, humidity, wind speed, water current, oxygen concentration, salinity, soil properties, etc.\nEnergy flow and nutrient cycling maintain the functioning of the ecosystem." },
      { q: "Describe the flow of energy in a food chain, and explain why energy decreases at each trophic level.", marks: "5 marks", answer: "Energy flows along the food chain from producers to consumers in the form of food.\nAt each trophic level, most energy is lost as heat (respiration), part is used for body activities and growth.\nOnly about 10% of the energy is converted into biomass and transferred to the next level.\nTherefore energy decreases at each level, and food chains usually have few trophic levels." },
      { q: "Compare a food chain and a food web, and explain the importance of food webs to the stability of an ecosystem.", marks: "4 marks", answer: "A food chain shows a single feeding pathway; a food web shows the complex, interconnected feeding relationships in an ecosystem.\nIn a food web, if the number of a prey species declines, predators can switch to other prey, so the system is more stable; the more complex the food web, the higher the stability." },
      { q: "Write down the role of decomposers in an ecosystem, and explain their importance to nutrient cycling.", marks: "4 marks", answer: "Decomposers (bacteria and fungi) break down dead organisms and wastes into inorganic substances (such as carbon dioxide and minerals).\nThese inorganic substances are reused by producers (e.g. photosynthesis, absorption of minerals), allowing nutrients (carbon, nitrogen, etc.) to cycle in the ecosystem.\nWithout decomposers, nutrients would be locked in organic matter and could not be recycled." },
      { q: "Describe the main processes of the carbon cycle, and explain how human activities affect the carbon cycle.", marks: "5 marks", answer: "Photosynthesis: producers absorb carbon dioxide to synthesise organic matter.\nRespiration: organisms break down organic matter and release carbon dioxide.\nCombustion: burning of fossil fuels releases carbon dioxide.\nDecomposers release carbon dioxide when they break down organic matter.\nHumans burn fossil fuels and cut down forests, increasing atmospheric carbon dioxide and intensifying the greenhouse effect and global warming." },
      { q: "Explain the difference between primary succession and secondary succession, giving one example of each.", marks: "4 marks", answer: "Primary succession: starts in bare places with no living organisms (e.g. a new island formed by volcanic eruption, bare rock), takes a long time, and begins with lichens and mosses.\nSecondary succession: the recovery of a community after it has been damaged but the soil remains (e.g. a forest after a fire); because soil and some species already exist, it takes a shorter time." },
      { q: "Compare the pyramid of numbers and the pyramid of biomass, and explain why the pyramid of numbers in the ocean may be inverted.", marks: "5 marks", answer: "The pyramid of numbers shows the number of organisms at each trophic level; the pyramid of biomass shows the total dry mass at each trophic level.\nIn the ocean the producers (phytoplankton) are small in size and numerous, but each is tiny and their biomass is small; the zooplankton are fewer but larger.\nBecause phytoplankton are extremely numerous, the pyramid of numbers can be inverted; the pyramid of biomass can also be inverted (as phytoplankton have low biomass but reproduce quickly with a high turnover rate)." },
      { q: "Write down the methods for investigating plant and animal population sizes (quadrat, capture–mark–recapture), and explain why random sampling is needed.", marks: "5 marks", answer: "Plants or stationary organisms: the quadrat method — randomly place square frames (quadrats) and count the organisms inside.\nAnimals: the capture–mark–recapture method — capture, mark, release, then recapture and estimate the population size by proportion.\nRandom sampling avoids subjective bias, making the sample representative so that the results better reflect the actual situation.\n(The line/belt transect method investigates the distribution of species along a line.)" },
      { q: "Explain why toxic substances (such as DDT) are present at higher concentrations in organisms at higher trophic levels (biomagnification).", marks: "4 marks", answer: "Toxic substances (such as DDT) are not easily broken down and accumulate in organisms.\nLower trophic level organisms take in small amounts; after being eaten by higher trophic level organisms, the toxin accumulates level by level along the food chain.\nBecause higher trophic levels must eat many lower level organisms, the toxin concentration in their bodies is higher than in their food.\nTherefore the higher the trophic level, the higher the concentration of toxic substances (biomagnification)." },
      { q: "Describe the difference between energy flow and nutrient flow in an ecosystem.", marks: "4 marks", answer: "Energy flow: energy flows one-way, from the Sun → producers → consumers, mostly lost as heat and cannot be recycled.\nNutrient flow: nutrients (carbon, nitrogen, water, etc.) are recycled between organisms and the environment; decomposers turn organic matter back into inorganic matter.\nEnergy requires a continuous input (the Sun), while nutrients can be recycled." },
      { q: "Explain how eutrophication causes the death of fish in a body of water.", marks: "6 marks", answer: "Fertilisers are leached into the water, causing algae to multiply rapidly.\nAlgae block sunlight, so aquatic plants at the bottom cannot get enough sunlight for photosynthesis and die, and the oxygen content of the water falls.\nAt night the algae carry out respiration, using up the oxygen in the water.\nWhen nutrients are exhausted the algae die, and bacteria decompose the mass of algae, further consuming the oxygen in the water.\nAquatic organisms (fish) die from lack of oxygen (suffocation)." },
      { q: "Write down the biotic and abiotic factors affecting the size of a population.", marks: "4 marks", answer: "Biotic factors: predation, competition, parasitism, disease, reproductive rate, food supply.\nAbiotic factors: temperature, light, rainfall, oxygen concentration, salinity, pH, space.\nThese factors affect the birth rate, death rate and migration of organisms, thus affecting the population size." },
      { q: "Explain why an ecosystem requires a continuous input of energy.", marks: "3 marks", answer: "Energy is mostly lost as heat when it flows along food chains and cannot be recycled.\nAn ecosystem must rely on a continuous input of solar energy (through photosynthesis by producers) to sustain life activities and the functioning of the ecosystem." }
    ]
  },
  {
    topicNo: 21,
    name: "Photosynthesis",
    questions: [
      { q: "An electron micrograph of an organelle shows the thylakoid membranes (A) and the stroma (B). Explain the functional relationship between A and B.", marks: "4 marks", answer: "The light-dependent reactions take place in A (the thylakoid membranes).\nThese reactions provide ATP energy and NADPH.\nSo that the light-independent reactions (Calvin cycle) can take place in B (the stroma).\nConversely, the light-independent reactions regenerate NADP, allowing the light-dependent reactions to continue in A." },
      { q: "What is the importance of the two products of the photochemical reactions to the whole process of photosynthesis?", marks: "4 marks", answer: "The photochemical reactions produce ATP.\nATP provides energy, driving the dark reactions / for the regeneration of the carbon dioxide acceptor.\nThe photochemical reactions also produce NADPH.\nNADPH provides reducing power to reduce the three-carbon compounds to produce glucose." },
      { q: "Write down the raw materials and products of photosynthesis, and explain its importance to life on Earth.", marks: "5 marks", answer: "Raw materials: carbon dioxide and water.\nProducts: glucose (carbohydrate) and oxygen.\nImportance: provides the basic food source; maintains the energy flow of ecosystems; maintains the balance of oxygen and carbon dioxide in the atmosphere.\nPhotosynthesis converts light energy into chemical energy stored in food." },
      { q: "Describe the location and process of the light reaction (including the photolysis of water and the production of oxygen).", marks: "5 marks", answer: "The light reaction takes place on the thylakoid membranes of the chloroplast.\nChlorophyll absorbs light energy, causing the photolysis of water: 2H₂O → 4H⁺ + 4e⁻ + O₂.\nATP and NADPH are produced (for use in the dark reaction).\nOxygen is a by-product, released to the atmosphere.\nThe light reaction requires light and chlorophyll." },
      { q: "Describe the location and process of the dark reaction (Calvin cycle).", marks: "4 marks", answer: "The dark reaction takes place in the stroma of the chloroplast.\nIt uses the ATP and NADPH produced by the light reaction to fix carbon dioxide.\nCarbon dioxide combines with a five-carbon compound and, through a series of reactions, forms a three-carbon compound, which is then reduced by NADPH and uses ATP to synthesise glucose.\nThe dark reaction does not require light directly, but needs the products of the light reaction; without light, the dark reaction also stops." },
      { q: "Explain why the rate of photosynthesis is affected by light intensity, carbon dioxide concentration and temperature.", marks: "6 marks", answer: "Light intensity: the stronger the light, the faster the light reaction and the higher the rate; it reaches saturation and is then limited by other factors.\nCarbon dioxide concentration: CO₂ is a raw material of the dark reaction; the higher the concentration, the higher the rate, until limited by other factors.\nTemperature: as temperature rises, enzyme activity rises and the rate increases; above the optimum temperature the enzymes are denatured and the rate falls.\nWhen any one factor becomes limiting, increasing it can raise the rate." },
      { q: "Explain the concept of a 'limiting factor', illustrating with photosynthesis.", marks: "4 marks", answer: "A limiting factor is the factor in shortest supply that limits the rate of a process; increasing that factor can raise the rate until it is no longer limiting.\nExample: in weak light, light intensity is the limiting factor, so increasing the light raises the rate of photosynthesis; when the light is sufficient, the carbon dioxide concentration becomes the limiting factor.\nIn agriculture, the yield of crops can be raised by increasing light, carbon dioxide and suitable temperature." },
      { q: "Describe the experimental steps for testing starch in a leaf, and explain the purpose of each step.", marks: "5 marks", answer: "1. Keep the plant in the dark for a period of time (to use up the starch originally present).\n2. Pick a leaf and put it in boiling water (to kill the cells and stop enzyme action).\n3. Soak the leaf in hot alcohol (to remove chlorophyll so that the colour change with iodine is clear).\n4. Rinse with water (to soften the leaf).\n5. Add iodine solution; turning blue-black shows starch is present (starch was produced by photosynthesis)." },
      { q: "In an experiment to show that light is needed for photosynthesis, why is part of the leaf covered? Predict and explain the result.", marks: "4 marks", answer: "Part of the leaf is covered with opaque paper as a control, to compare the illuminated and unilluminated parts.\nResult: the exposed part turns blue-black (contains starch), the covered part does not change (no starch).\nThis shows that photosynthesis requires light; only the illuminated part can carry out photosynthesis to produce starch." },
      { q: "In an experiment to show that carbon dioxide is needed for photosynthesis, why is sodium hydroxide solution used? Predict and explain the result.", marks: "4 marks", answer: "Sodium hydroxide solution absorbs the carbon dioxide in the jar, so the experimental group has no carbon dioxide.\nThe leaf in the experimental group (with sodium hydroxide) does not turn blue-black with iodine (no starch); the leaf in the control group (with water) turns blue-black.\nThis shows that photosynthesis requires carbon dioxide; without carbon dioxide, food (starch) cannot be made." },
      { q: "Explain why aquatic plants (such as Elodea) release bubbles of oxygen in the light, and explain how this phenomenon can be used to measure the rate of photosynthesis.", marks: "4 marks", answer: "Aquatic plants carry out photosynthesis in the light, and the photolysis of water produces oxygen, which is released from the leaf surface as bubbles.\nThe number of bubbles released per unit time (or the volume of gas collected) can be counted as an indicator of the rate of photosynthesis.\nThe more bubbles, the higher the rate of photosynthesis; light intensity, temperature and CO₂ concentration affect the number of bubbles." },
      { q: "Write down the adaptations of a leaf for absorbing light energy, gas exchange, transport and reducing water loss.", marks: "6 marks", answer: "Absorbing light energy: the leaf blade is broad and flat, the leaf is very thin, the network of veins supports the blade, and the palisade mesophyll is in the upper layer containing many chloroplasts.\nGas exchange: the leaf is thin, shortening the diffusion distance for carbon dioxide; there are many stomata and guard cells control their opening.\nTransport: the leaf veins contain vascular bundles (xylem + phloem), with a network ensuring effective transport.\nReducing water loss: the upper and lower epidermises have a cuticle; terrestrial plants generally have fewer stomata on the upper epidermis than on the lower." },
      { q: "Compare the light reaction and the dark reaction in terms of location, conditions and products.", marks: "5 marks", answer: "Location: the light reaction is on the thylakoid membranes, the dark reaction is in the stroma.\nConditions: the light reaction requires light and water; the dark reaction does not require light but requires ATP and NADPH.\nProducts: the light reaction produces ATP, NADPH and oxygen; the dark reaction fixes carbon dioxide and produces glucose.\nThe two are interdependent: the light reaction supplies the energy and reducing power needed by the dark reaction." },
      { q: "Explain why the chloroplast is described as the 'food-manufacturing factory' of the cell.", marks: "4 marks", answer: "The chloroplast contains chlorophyll, which can absorb light energy.\nThe chloroplast carries out photosynthesis, synthesising organic food (glucose) from inorganic substances (carbon dioxide and water).\nThe food made provides the energy source for the plant and other organisms.\nTherefore the chloroplast is the site where the cell manufactures food." },
      { q: "A student placed a plant in a sealed transparent container and left it in the light for a period of time.\n(a) What changes occur in the carbon dioxide and oxygen concentrations in the container?\n(b) Explain the reasons.", marks: "4 marks", answer: "(a) The carbon dioxide concentration falls and the oxygen concentration rises.\n(b) In the light the plant carries out photosynthesis, absorbing carbon dioxide and releasing oxygen; when photosynthesis exceeds respiration, carbon dioxide decreases net and oxygen increases net.\n(In the dark the opposite happens: only respiration occurs, carbon dioxide rises and oxygen falls.)" }
    ]
  },
  {
    topicNo: 22,
    name: "Respiration",
    questions: [
      { q: "An athlete ran for ten minutes and his blood lactate concentration increased. Explain this phenomenon, and compare the effectiveness of sitting down and walking slowly in removing lactate.", marks: "6 marks", answer: "During vigorous exercise the energy demand increases and the oxygen supply is insufficient to meet the energy needs of the muscles.\nThe muscles carry out anaerobic respiration to release extra energy for muscle contraction.\nAnaerobic respiration produces lactic acid, so the blood lactate concentration increases.\nA large amount of lactic acid lowers the pH of the blood/tissue fluid, which has adverse effects on cell activities.\nWalking slowly is more effective: walking slowly maintains a higher heart rate / blood flow rate, increasing the rate of oxygen supply to the body.\nThis promotes the breakdown of lactic acid / the conversion of lactic acid into glycogen." },
      { q: "Compare aerobic respiration and anaerobic respiration in terms of products, energy released and location.", marks: "5 marks", answer: "Products of aerobic respiration: carbon dioxide, water and a large amount of energy (ATP); products of anaerobic respiration: lactic acid (animal muscles) or ethanol + carbon dioxide (yeast).\nAerobic respiration releases far more energy than anaerobic respiration.\nAerobic respiration requires oxygen as the final electron acceptor; anaerobic respiration does not.\nBoth begin with glycolysis in the cytoplasm; the rest of aerobic respiration takes place in the mitochondria, while anaerobic respiration takes place entirely in the cytoplasm." },
      { q: "Describe the four stages of aerobic respiration and their locations.", marks: "6 marks", answer: "Glycolysis (cytoplasm): glucose → 2 triose phosphates → 2 pyruvate, net production of 2ATP and 2NADH.\nLink reaction (mitochondrial matrix): pyruvate → acetyl coenzyme A, producing 2CO₂ and 2NADH.\nKrebs cycle (mitochondrial matrix): producing 4CO₂, 6NADH, 2FADH and 2ATP.\nOxidative phosphorylation (inner mitochondrial membrane): NADH and FADH act as hydrogen donors, electrons travel along the electron transport chain and are finally accepted by oxygen to form water; 1 NADH produces 3ATP and 1 FADH produces 2ATP." },
      { q: "Explain why anaerobic respiration releases far less energy than aerobic respiration.", marks: "4 marks", answer: "Anaerobic respiration only carries out glycolysis, so glucose is only partially broken down and most energy remains in the products (lactic acid or ethanol).\nAnaerobic respiration produces only 2 ATP per glucose molecule.\nAerobic respiration completely oxidises glucose into carbon dioxide and water, producing a large amount of ATP (about 38).\nTherefore anaerobic respiration releases far less energy than aerobic respiration." },
      { q: "Explain the concept of oxygen debt, and describe how the body repays the oxygen debt after exercise.", marks: "5 marks", answer: "Oxygen debt is the extra oxygen that must be taken in after vigorous exercise, to break down the accumulated lactic acid.\nDuring vigorous exercise the oxygen supply is insufficient and the muscles carry out anaerobic respiration, producing lactic acid.\nAfter exercise the breathing rate remains high, supplying extra oxygen.\nThe extra oxygen breaks down the lactic acid into carbon dioxide and water (or converts it into glycogen).\nWhen the lactic acid is removed, the body returns to normal." },
      { q: "Write down the difference between respiration and breathing (ventilation), giving examples.", marks: "4 marks", answer: "Respiration: the process of breaking down organic matter in cells to release energy, which takes place in the cytoplasm and mitochondria, e.g. the breakdown of glucose to produce ATP.\nBreathing (ventilation): the movement of gases into and out of the body, e.g. inhalation and exhalation.\nThe two have similar names but completely different meanings; lime water turning milky can be used to show that respiration produces carbon dioxide." },
      { q: "Describe experiments to show that germinating seeds carry out respiration (consuming oxygen, producing carbon dioxide and heat).", marks: "5 marks", answer: "Consuming oxygen: put germinating seeds in a sealed jar containing lime water or measure the oxygen; observe the air pressure falling / oxygen decreasing (a burning candle goes out).\nProducing carbon dioxide: seal germinating seeds with lime water; the lime water turns milky.\nProducing heat: put germinating seeds in a vacuum flask and measure the temperature rise; in the control using boiled seeds, the temperature does not rise.\nThe results show that germinating seeds carry out respiration." },
      { q: "Explain why muscles ache after vigorous exercise.", marks: "4 marks", answer: "During vigorous exercise the oxygen supply is insufficient, so the muscles carry out anaerobic respiration and produce lactic acid.\nThe lactic acid accumulates in the muscles, stimulating nerve endings and causing an aching sensation.\nLactic acid also lowers the pH of the muscles, affecting muscle function.\nAfter rest and with an adequate oxygen supply the lactic acid is broken down and the ache subsides." },
      { q: "Compare glycolysis and oxidative phosphorylation in terms of location and products.", marks: "4 marks", answer: "Glycolysis: takes place in the cytoplasm, glucose is broken down into pyruvate, producing a net 2ATP and 2NADH, and does not require oxygen.\nOxidative phosphorylation: takes place on the inner mitochondrial membrane; NADH and FADH provide electrons that travel along the electron transport chain, finally accepted by oxygen to form water, producing a large amount of ATP; it requires oxygen.\nOxidative phosphorylation is the only stage that uses oxygen; without oxygen, NAD and FAD cannot be regenerated and the aerobic pathway stops." },
      { q: "Explain why yeast carries out anaerobic respiration in the absence of oxygen to produce ethanol and carbon dioxide, whereas muscle cells produce lactic acid.", marks: "4 marks", answer: "Both carry out glycolysis to produce pyruvate and NADH.\nWithout oxygen, NADH must be re-oxidised to NAD to allow glycolysis to continue.\nYeast converts pyruvate into ethanol and carbon dioxide; muscle cells convert pyruvate into lactic acid.\nBoth methods regenerate NAD, but the products differ; the energy released is the same (2ATP each)." },
      { q: "Write down the factors affecting the rate of respiration, and explain how temperature affects it.", marks: "4 marks", answer: "Factors: temperature, oxygen supply, substrate (food) supply, enzyme activity, etc.\nTemperature: as temperature rises, enzyme activity rises and the rate of respiration increases; above the optimum temperature the enzymes are denatured and the rate falls.\n(Respiration is controlled by enzymes, so temperature affects enzyme activity and hence the rate of respiration.)" },
      { q: "State the similarities between aerobic respiration and anaerobic respiration.", marks: "4 marks", answer: "Both are oxidation processes (breaking down organic matter).\nBoth release part of the energy to produce ATP.\nBoth are controlled by enzymes.\nBoth begin with glycolysis (in the cytoplasm, glucose broken down into pyruvate)." },
      { q: "An athlete breathes in oxygen before a competition. Explain whether this helps improve performance, and its limitation.", marks: "4 marks", answer: "Haemoglobin in the blood is already nearly saturated with oxygen, so inhaling extra oxygen adds little and helps little in improving performance.\nPerformance is mainly limited by cardiorespiratory function and muscle metabolic capacity.\nWhat limits performance during exercise is the rate of oxygen transport and supply, not the oxygen concentration in the air inhaled.\nTherefore inhaling pure oxygen before competition helps most athletes only a little." },
      { q: "Explain why the mitochondrion is described as the 'powerhouse' of the cell.", marks: "4 marks", answer: "The mitochondrion is the main site of aerobic respiration, breaking down organic food to release energy.\nThe energy is mainly stored in the form of ATP for the various activities of the cell.\nThe inner mitochondrial membrane is highly folded (cristae), increasing the surface area to accommodate more enzymes and carriers, raising the efficiency of ATP synthesis.\nCells with high energy demand (e.g. muscles, sperm) contain more mitochondria." },
      { q: "Describe the significance of respiration, and explain why it is indispensable to all organisms.", marks: "4 marks", answer: "Respiration releases the energy in the organic matter of food, storing it in the form of ATP.\nATP provides energy for the various life activities of cells (movement, growth, synthesis, active transport, maintaining body temperature, etc.).\nAll organisms need energy to sustain life, so respiration is indispensable.\nRespiration also produces intermediate products for the synthesis of other substances." }
    ]
  },
  {
    topicNo: 23,
    name: "Personal Health and Infectious Diseases",
    questions: [
      { q: "Explain why increasing the use of antibiotics causes the percentage of antibiotic-resistant bacteria in the population to rise.", marks: "5 marks", answer: "There is genetic variation in the bacterial population, and some bacteria are resistant to antibiotics.\nIncreased use of antibiotics kills the non-resistant bacteria, while the resistant bacteria survive.\nThe resistant bacteria keep reproducing, producing offspring with the same characteristics.\nCompetition for nutrients and other resources in the population decreases, so the number of resistant bacteria increases faster.\nTherefore the percentage of resistant bacteria in the population rises." },
      { q: "Write down two serious consequences of the misuse of antibiotics.", marks: "4 marks", answer: "Bacteria with resistance to many antibiotics (superbugs) may appear; diseases caused by superbugs may be untreatable, threatening human health.\nAntibiotics kill both beneficial and pathogenic bacteria at the same time, reducing the competition faced by pathogens and promoting their growth.\nNew antibiotics or other drugs are needed to replace ineffective ones, and developing new drugs requires more money and manpower. (any two)" },
      { q: "Write down the routes of transmission of infectious diseases, giving one example disease for each.", marks: "5 marks", answer: "Droplets: tuberculosis, common cold.\nFood and water: cholera.\nVectors (mosquitoes): malaria, dengue fever.\nBlood/body fluids: hepatitis B, AIDS.\nContact: skin infections (e.g. ringworm).\n(Write down the main routes with examples.)" },
      { q: "Compare viruses and bacteria, and explain why antibiotics are ineffective against viral diseases.", marks: "5 marks", answer: "Bacteria are cells with a cell wall, cell membrane, cytoplasm and DNA; viruses are not cells, are smaller than bacteria, and must parasitise living cells to reproduce.\nAntibiotics can kill bacteria or inhibit their growth (e.g. inhibiting cell wall synthesis, protein synthesis).\nViruses do not have these structures and mechanisms that antibiotics act on.\nTherefore antibiotics are ineffective against viruses; viral diseases are dealt with by the immune system and antiviral drugs." },
      { q: "Describe the principle of vaccination, and explain why vaccination is artificial active immunity.", marks: "5 marks", answer: "Vaccines contain antigens (weakened or killed pathogens or their parts).\nAfter vaccination, the antigens stimulate the immune system to produce antibodies and memory cells.\nOn re-exposure to the same pathogen, the memory cells rapidly produce large amounts of antibodies (secondary response), protecting the body.\nSince the antibodies are produced by the body's own immune system and the antigens are introduced artificially, vaccination is artificial active immunity." },
      { q: "Explain why antibiotics should be prescribed only when needed and the whole course should be completed.", marks: "4 marks", answer: "Misuse of antibiotics selects for resistant bacteria, making the antibiotics ineffective.\nPrescribing antibiotics only when needed reduces the selection pressure and delays the development of resistance.\nCompleting the whole course ensures that all bacteria (including resistant mutants) are eliminated, preventing surviving resistant bacteria from multiplying.\nUsing narrow-spectrum antibiotics reduces the killing of beneficial bacteria." },
      { q: "Write down the personal hygiene and public health measures to prevent infectious diseases.", marks: "5 marks", answer: "Personal hygiene: wash hands frequently, cover the mouth and nose when coughing or sneezing, do not share towels, keep personal cleanliness.\nPublic health: isolate patients, disinfect the environment, drink boiled water, deal with stagnant water (to prevent mosquitoes), vaccination programmes, sewage treatment.\nVaccination is an important preventive measure (artificial active immunity)." },
      { q: "Explain why malaria is difficult to spread in cold regions but is common in tropical regions.", marks: "4 marks", answer: "Malaria is caused by Plasmodium (a protozoan), transmitted by the bite of female Anopheles mosquitoes.\nAnopheles mosquitoes reproduce rapidly in warm, humid tropical environments and are numerous.\nIn cold regions the temperature is too low for the mosquitoes to survive and reproduce, and the development of Plasmodium in the mosquito also requires higher temperatures.\nTherefore malaria is common in the tropics and rare in cold regions." },
      { q: "Write down the pathogen and transmission routes of AIDS, and explain why AIDS patients are susceptible to other infections.", marks: "4 marks", answer: "Pathogen: human immunodeficiency virus (HIV).\nTransmission routes: blood, sexual contact, mother-to-child transmission.\nHIV attacks and destroys helper T cells, weakening the immune system (cell-mediated immunity is damaged).\nWith a weakened immune system the body cannot effectively fight other pathogens, so patients are susceptible to opportunistic infections." },
      { q: "Explain why viruses are not cells, and how this affects their way of survival.", marks: "4 marks", answer: "Viruses have no cell membrane, cytoplasm or nucleus; they consist only of nucleic acid (DNA or RNA) and a protein coat.\nViruses cannot carry out metabolism independently and must parasitise living cells, using the host cell's machinery to replicate.\nOutside a living cell viruses cannot reproduce, so they must enter a host cell to multiply." },
      { q: "Describe how resistant bacteria arise (the process of natural selection).", marks: "5 marks", answer: "Genetic variation arises in the bacterial population through mutation, and some bacteria have resistant traits.\nUsing antibiotics kills the non-resistant bacteria, and the resistant bacteria survive.\nThe surviving resistant bacteria reproduce, passing the resistance gene to their offspring.\nAfter many generations the proportion of resistant bacteria in the population rises and the antibiotic gradually becomes ineffective.\nThis shows that natural selection can change the gene composition of a population (evolution)." },
      { q: "Write down the pathogen, transmission route and prevention of cholera.", marks: "4 marks", answer: "Pathogen: Vibrio cholerae (a bacterium).\nTransmission route: drinking contaminated water or eating contaminated food.\nSymptom: severe diarrhoea and dehydration.\nPrevention: drink boiled water, pay attention to food hygiene, wash hands, dispose of sewage and faeces properly, vaccination." },
      { q: "Explain why using insecticides and dealing with stagnant water can prevent dengue fever.", marks: "3 marks", answer: "Dengue fever is caused by the dengue virus, transmitted by the bite of Aedes aegypti and Aedes albopictus mosquitoes.\nDealing with stagnant water eliminates the breeding sites of the mosquitoes (larval habitats), reducing the mosquito population.\nInsecticides can kill adult mosquitoes.\nReducing the mosquito vector population cuts off the transmission route, preventing dengue fever." },
      { q: "Compare infectious diseases and non-infectious diseases, giving two examples of each.", marks: "4 marks", answer: "Infectious diseases: caused by pathogens, can spread from person to person or through transmission routes, e.g. cholera, tuberculosis, AIDS.\nNon-infectious diseases: not caused by pathogens, cannot spread between people, e.g. diabetes, coronary heart disease, cancer.\nNon-infectious diseases are mainly related to lifestyle, genetics and environmental factors." },
      { q: "Explain why a vaccinated person may still contract the disease.", marks: "4 marks", answer: "The immunity induced by a vaccine is not 100%; some people have a weak immune response.\nThe pathogen may mutate (e.g. influenza virus), changing the antigen targeted by the vaccine, so the existing antibodies and memory cells cannot recognise it.\nImmunological memory may weaken over time, and boosters are needed.\nIf the person is exposed to the pathogen before immunity is established (during the incubation period), infection may still occur." }
    ]
  },
  {
    topicNo: 24,
    name: "Non-infectious Diseases and Disease Prevention",
    questions: [
      { q: "Mr Chan has smoked for more than 25 years and experiences chest pain during vigorous exercise. The doctor advised him to quit smoking and adopt a low-fat diet. Give a reason for each piece of advice.", marks: "4 marks", answer: "Quitting smoking: carbon monoxide produced by burning tobacco reduces the oxygen-carrying capacity of the blood; quitting increases the oxygen content of the blood; or nicotine constricts blood vessels, increasing the workload of the heart.\nLow-fat diet: a low-fat diet reduces the deposition of fatty substances on the walls of the coronary arteries, reducing the risk of atherosclerosis." },
      { q: "Explain why coronary heart disease is the number one killer in high-income countries; and give one example of how a lifestyle is related to coronary heart disease.", marks: "5 marks", answer: "Residents of high-income countries often eat high-calorie/high-fat food and lack exercise.\nThis increases the formation of cholesterol plaques / fat deposition in the coronary arteries.\nThe lumen of the arteries narrows and blood flow decreases.\nThe heart muscle is not supplied with enough nutrients and oxygen.\nThis leads to heart disease (coronary heart disease)." },
      { q: "Explain the cause of cancer, and compare benign tumours and malignant tumours.", marks: "5 marks", answer: "Cause: mutations in the DNA related to cell division make cells divide uncontrollably, forming tumours.\nBenign tumours: surrounded by connective tissue, stay at the site of origin, and do not spread.\nMalignant tumours: not surrounded, can spread through the blood or lymphatic system and invade other tissues (metastasis), i.e. cancer.\nRisk factors include smoking, carcinogens, radiation and heredity." },
      { q: "Write down the causes, symptoms and treatment of coronary heart disease.", marks: "5 marks", answer: "Cause: atherosclerosis of the coronary arteries (cholesterol deposits forming atheromas), narrowing or blocking of the lumen, insufficient blood supply to the heart muscle.\nSymptoms: chest pain during vigorous exercise (angina), heart attack.\nTreatment: balloon angioplasty, coronary artery bypass surgery, medication, lifestyle changes.\nRisk factors: high-fat diet, smoking, lack of exercise, high blood pressure, diabetes, heredity." },
      { q: "Explain how smoking damages the cardiovascular and respiratory systems.", marks: "5 marks", answer: "Nicotine: constricts blood vessels, stimulates the heart rate, increases platelet stickiness, raising blood pressure and the workload of the heart.\nCarbon monoxide: combines with haemoglobin, reducing the oxygen-carrying capacity of the blood.\nTar: deposited in the lungs, damaging the alveoli and cilia, increasing the risk of lung cancer and chronic obstructive pulmonary disease.\nSmoke irritates the airways, increasing mucus secretion and narrowing them, affecting breathing." },
      { q: "Write down the risk factors, symptoms and prevention of type 2 diabetes.", marks: "5 marks", answer: "Risk factors: obesity, overeating, lack of exercise, heredity.\nSymptoms: frequent urination, thirst, tiredness, hunger.\nPrevention: healthy diet (low sugar, low fat), regular exercise, weight control, regular screening.\nThe target cells of type 2 diabetic patients do not respond to insulin, mainly related to unhealthy lifestyles." },
      { q: "Explain the importance of health screening in preventing diseases.", marks: "3 marks", answer: "Health screening helps detect diseases early before symptoms appear (e.g. diabetes, high blood pressure, cancer).\nEarly detection allows early treatment, raising the cure rate and reducing complications.\nScreening helps identify high-risk people and take preventive measures, improving health." },
      { q: "Write down the benefits of a balanced diet and regular exercise in preventing non-infectious diseases.", marks: "5 marks", answer: "Balanced diet: eat more fruit and vegetables and reduce saturated fat and salt, lowering the risk of obesity, high blood pressure, coronary heart disease and diabetes.\nRegular exercise: improves heart and lung function, controls body weight, improves blood glucose and blood pressure, relieves stress, and reduces the risk of cardiovascular disease and diabetes.\nCombining the two can significantly reduce the risk of non-infectious diseases." },
      { q: "Explain the formation of atherosclerosis and its consequences.", marks: "5 marks", answer: "A high-fat diet raises blood cholesterol.\nCholesterol and other fatty substances are deposited on the inner walls of the arteries, forming atheromas.\nThe lumen narrows and the walls harden (lose elasticity).\nBlood pressure rises and blood flow decreases, so the heart muscle or brain tissue is under-supplied.\nIf an atheroma ruptures and forms a thrombus that blocks the vessel, a heart attack or stroke may occur." },
      { q: "Write down the causes and consequences of stroke.", marks: "4 marks", answer: "Cause: blockage of a brain artery (thrombus) or bursting (haemorrhage).\nBrain cells die from lack of oxygen.\nConsequences: loss of some body functions (paralysis, speech disorder); in severe cases, death.\nPrevention: control blood pressure, low-fat diet, quit smoking, regular exercise." },
      { q: "Explain why excessive exposure to ultraviolet light increases the risk of skin cancer.", marks: "3 marks", answer: "Ultraviolet light is a mutagen that can damage the DNA of skin cells, causing gene mutations.\nThe accumulation of mutations makes skin cells divide uncontrollably, forming skin cancer.\nAvoiding excessive exposure and using sunscreen can reduce the risk." },
      { q: "Write down the treatments for cancer, and explain the importance of early detection to treatment.", marks: "4 marks", answer: "Treatment: surgical removal of the tumour, chemotherapy, radiotherapy, targeted therapy, immunotherapy.\nWhen detected early, the tumour is smaller and has not metastasised, so surgical removal has a high success rate and the treatment outcome is better.\nAdvanced cancer has metastasised and is difficult to treat, with a poorer prognosis; therefore regular screening and early detection are very important." },
      { q: "Explain the effects of long-term alcohol abuse on the body.", marks: "4 marks", answer: "Alcohol is broken down in the liver; long-term alcohol abuse damages the liver, causing fatty liver, hepatitis and cirrhosis.\nIt increases the risk of high blood pressure, stroke and certain cancers (liver cancer).\nIt damages the nervous system (memory and judgement), and affects nutrient absorption.\nAlcohol abuse also increases accidents and social problems." },
      { q: "Compare type 1 and type 2 diabetes in terms of age of onset, causes and treatment.", marks: "5 marks", answer: "Type 1: usually develops in young people; the beta cells of the pancreas are destroyed by the immune system and cannot make or make only a little insulin; insulin must be injected.\nType 2: usually develops in adulthood; the target cells do not respond to insulin (insulin resistance); related to obesity and lack of exercise; controlled by diet and exercise, with medication in severe cases.\nBoth have high blood glucose, but the causes and treatment differ." },
      { q: "A patient's blood pressure has been high for a long time. Explain the causes and dangers of high blood pressure, and suggest ways to improve it.", marks: "5 marks", answer: "Causes: high-salt diet, obesity, lack of exercise, smoking, heredity, etc.\nDangers: increases the workload of the heart, damages the arteries (atherosclerosis), and increases the risk of heart disease, stroke and kidney disease.\nImprovement: low-salt, low-fat diet, regular exercise, weight control, quit smoking, stress reduction; in severe cases, take blood pressure medication.\nRegular measurement of blood pressure helps early detection and control." }
    ]
  },
  {
    topicNo: 25,
    name: "Body Defence Mechanisms",
    questions: [
      { q: "Explain why a child who has been vaccinated is better protected than a child who has not.", marks: "4 marks", answer: "The vaccine contains antigens.\nThese antigens stimulate the immune system, producing memory cells related to them.\nOn the second contact with the same antigen, the memory cells have the ability to produce a large amount of antibody.\nTherefore a vaccinated child usually has a higher level of antibody and is better protected." },
      { q: "Explain why inflamed tissues often show redness, swelling and pain.", marks: "4 marks", answer: "During inflammation, the small arteries of the tissue dilate, increasing blood flow to the tissue, making it red.\nThe permeability of the capillary walls increases, increasing the formation and accumulation of tissue fluid, making it swell.\nMore tissue fluid presses on the nerve endings, stimulating the pain receptors.\nTherefore a feeling of pain is produced." },
      { q: "Write down the non-specific defence mechanisms of the body (the first and second lines of defence).", marks: "5 marks", answer: "First line of defence: physical barriers (the skin, mucus and cilia of the respiratory mucosa); chemical barriers (gastric acid, lysozyme in tears).\nSecond line of defence: phagocytosis (phagocytes engulf pathogens); blood clotting (fibrin traps pathogens); inflammatory response.\nThese defences act against all pathogens and are not specific." },
      { q: "Describe the humoral (B cell) and cell-mediated (T cell) immune responses in specific immunity.", marks: "6 marks", answer: "Humoral immunity: after a B cell binds an antigen and is stimulated by a helper T cell, it differentiates into plasma cells (producing antibodies) and memory B cells.\nCell-mediated immunity: helper T cells are activated and secrete lymphokines, stimulating killer T cells to destroy infected cells.\nThe primary response is slow and small; the secondary response is fast and large (because of memory cells).\nFunctions of antibodies: dissolving pathogens, coating antigens to promote phagocytosis, clumping pathogens together, neutralising toxins." },
      { q: "Compare active immunity and passive immunity, giving one example of each.", marks: "5 marks", answer: "Active immunity: antibodies are produced by the body's own immune system and immunity is long-lasting; natural (recovery from illness), artificial (vaccination).\nPassive immunity: antibodies are introduced from outside, giving immediate but short-lived immunity; natural (from the mother via the placenta/breast milk), artificial (injection of antiserum).\nActive immunity produces memory cells and long-lasting immunity; passive immunity has no memory and is short-lived." },
      { q: "Explain how vaccination produces immunological memory, and describe the response on re-exposure to the pathogen.", marks: "5 marks", answer: "A vaccine introduces antigens, activating B cells and T cells.\nSome of the activated cells differentiate into memory cells that survive in the body for a long time.\nOn re-exposure to the same antigen, the memory cells rapidly proliferate and differentiate into plasma cells, producing large amounts of antibody.\nThe secondary response is faster, stronger and larger, so immune protection is more effective." },
      { q: "Write down the nature and four functions of antibodies.", marks: "4 marks", answer: "Antibodies are proteins secreted by plasma cells, with high specificity.\nFunctions: dissolving pathogens (lysis), coating antigens to promote phagocytosis, clumping pathogens together (agglutination), neutralising toxins (antitoxins).\nAntibodies bind specifically to their corresponding antigens, helping to remove pathogens." },
      { q: "Describe how phagocytes destroy pathogens.", marks: "4 marks", answer: "A phagocyte approaches a pathogen and extends pseudopodia to surround it.\nIt engulfs the pathogen into the cell (phagocytosis), forming a phagosome.\nA lysosome fuses with the phagosome and releases digestive enzymes to break down the pathogen.\nThe indigestible remains are expelled and useful materials are used by the cell.\nPhagocytosis is a non-specific defence that is effective against all pathogens." },
      { q: "Explain how the skin and mucous membranes act as the first line of defence.", marks: "4 marks", answer: "Skin: forms a physical barrier preventing pathogens from entering; the substances secreted on the skin surface and the dry condition are unfavourable to pathogen survival; the cornified layer is tough.\nMucous membranes: the mucus secreted by the respiratory mucosa traps pathogens, and the cilia move the mucus carrying pathogens upwards and away; tears and gastric juice contain germ-killing substances (lysozyme, hydrochloric acid).\nThese are the first line of defence, preventing the invasion of pathogens." },
      { q: "Explain why maternal antibodies can protect a newborn baby, but this protection is only temporary.", marks: "4 marks", answer: "Maternal antibodies are passed to the baby through the placenta or breast milk, providing immediate immune protection.\nThese antibodies come from the mother, and the baby has not produced corresponding memory cells itself.\nThe antibodies are broken down over time and their level falls, so the baby is no longer protected.\nThis is natural passive immunity, which is short-lived; the baby needs vaccination to build up its own immunity." },
      { q: "Describe the process of blood clotting, and explain its defensive role.", marks: "4 marks", answer: "When the skin is injured, platelets gather at the wound and release clotting factors.\nFibrinogen is converted into insoluble fibrin, forming a network.\nThe fibrin network traps blood cells and pathogens, forming a clot.\nThe clot seals the wound, preventing further blood loss and the entry of pathogens, and is an important defence mechanism." },
      { q: "Compare the primary immune response and the secondary immune response.", marks: "4 marks", answer: "Primary response: on first contact with the antigen, there is a long lag period, a low antibody level and a short duration.\nSecondary response: on the second contact with the same antigen, because of memory cells, the response is fast, the antibody level is high and the duration is long.\nThe strength and speed of the secondary response are far greater than those of the primary response, providing more effective protection.\nThis is why vaccination can prevent disease." },
      { q: "Explain why immunosuppressive drugs are needed after organ transplantation.", marks: "4 marks", answer: "The cells of the transplanted organ carry antigens (donor MHC molecules) not present in the recipient.\nThe recipient's immune system recognises the transplanted organ as 'non-self' and mounts an immune attack, rejecting the organ.\nImmunosuppressive drugs suppress the immune response, reducing rejection.\nBut immunosuppression also increases the risk of infection, so a careful balance is needed." },
      { q: "Write down the effect of HIV on the immune system, and explain why AIDS patients are susceptible to infections.", marks: "5 marks", answer: "HIV attacks and destroys helper T cells.\nHelper T cells play a key role in the immune response, helping B cells and killer T cells.\nWhen the number of helper T cells drops greatly, the function of the immune system is damaged.\nThe body cannot cope with pathogens effectively, so patients are susceptible to opportunistic infections and certain cancers.\nVaccines and drugs (antiretroviral therapy) can delay the disease but cannot cure it." },
      { q: "Explain the role of the inflammatory response, and how it helps the body fight infection.", marks: "5 marks", answer: "When tissue is damaged or infected, the small arteries dilate, increasing blood flow (redness, heat).\nThe permeability of the capillaries increases, so tissue fluid and phagocytes leak out (swelling).\nPhagocytes gather at the infected site and engulf pathogens.\nThe tissue fluid presses on the nerve endings, producing pain that reminds the body to protect the area.\nThe inflammatory response mobilises immune cells to fight infection and is an important part of non-specific defence." }
    ]
  }
];
